import type { DeckCardType, DeckStatus, DeckVisibility } from '@/types/deckAdmin'

export const DECK_ADMIN_ERROR_MESSAGES: Record<string, string> = {
  Deck_NotFound_404: 'Không tìm thấy bộ thẻ.',
  Deck_FolderNotFound_404: 'Không tìm thấy thư mục trong bộ thẻ.',
  Deck_CardNotFound_404: 'Không tìm thấy thẻ cần thao tác.',
  Deck_CardDuplicatedInDeck_400: 'Thẻ này đã tồn tại ở thư mục khác trong cùng bộ thẻ.',
  Deck_InvalidReorderPayload_400: 'Dữ liệu sắp xếp không hợp lệ. Vui lòng tải lại và thử lại.',
  DeckType_NotFound_404: 'Không tìm thấy loại bộ thẻ.',
  DeckType_NameExists_409: 'Tên loại bộ thẻ đã tồn tại.',
  DeckType_InUse_400: 'Loại bộ thẻ này đang được sử dụng nên chưa thể xóa.',
}

export const DECK_ADMIN_STATUS_LABELS: Record<DeckStatus, string> = {
  Draft: 'Nháp',
  Published: 'Đã phát hành',
  Archived: 'Đã lưu trữ',
}

export const DECK_ADMIN_VISIBILITY_LABELS: Record<DeckVisibility, string> = {
  Public: 'Công khai',
  Private: 'Riêng tư',
}

export const DECK_ADMIN_CARD_TYPE_LABELS: Record<DeckCardType, string> = {
  Vocab: 'Từ vựng',
  Grammar: 'Ngữ pháp',
  Kanji: 'Hán tự',
}

export const ADMIN_DECK_CONTENT = {
  pageTitle: 'Quản lý bộ thẻ',
  heading: 'Quản lý bộ thẻ',
  description: 'Kiểm soát danh sách bộ thẻ, trạng thái phát hành, thư mục và thẻ học trong từng bộ.',
  searchPlaceholder: 'Tìm theo tiêu đề hoặc mô tả bộ thẻ...',
  createLabel: 'Tạo bộ thẻ',
  manageTypesLabel: 'Quản lý loại bộ thẻ',
  tableTitle: 'Danh sách bộ thẻ',
  emptyTitle: 'Không có bộ thẻ phù hợp',
  emptyDescription: 'Hãy thử đổi bộ lọc hoặc tạo một bộ thẻ mới.',
  emptyActionLabel: 'Tạo bộ thẻ',
  resultCountLabel: (count: number) => `${count} bộ thẻ`,
  filterTitle: 'Bộ lọc bộ thẻ',
  filterDescription: 'Lọc theo trạng thái, hiển thị, loại bộ thẻ và cờ hệ thống.',
  activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
  typeFilterPlaceholder: 'Chọn loại bộ thẻ',
  statusFilterPlaceholder: 'Chọn trạng thái',
  visibilityFilterPlaceholder: 'Chọn hiển thị',
  officialOnlyLabel: 'Chỉ hiện bộ thẻ hệ thống',
  resetFiltersLabel: 'Xóa lọc',
  searchLabel: 'Tìm kiếm',
  allOptionLabel: 'Tất cả',
  previousPageLabel: 'Trang trước',
  nextPageLabel: 'Trang sau',
  columns: {
    title: 'Bộ thẻ',
    type: 'Loại',
    owner: 'Người tạo',
    status: 'Trạng thái',
    visibility: 'Hiển thị',
    official: 'Hệ thống',
    counters: 'Số lượng',
    updatedAt: 'Cập nhật',
    actions: 'Thao tác',
  },
  statusActions: {
    publish: 'Phát hành',
    unpublish: 'Chuyển về nháp',
    archive: 'Lưu trữ',
  },
  actions: {
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    openDetail: 'Mở trình chỉnh sửa',
  },
  confirmDeleteTitle: 'Xóa bộ thẻ?',
  confirmDeleteDescription: 'Hành động này sẽ xóa toàn bộ thư mục, thẻ liên kết và bookmark liên quan.',
  confirmDeleteAction: 'Xóa bộ thẻ',
  confirmCancelLabel: 'Hủy',
  toast: {
    createSuccess: 'Đã tạo bộ thẻ thành công.',
    updateSuccess: 'Đã cập nhật bộ thẻ thành công.',
    deleteSuccess: 'Đã xóa bộ thẻ thành công.',
    publishSuccess: 'Đã phát hành bộ thẻ.',
    unpublishSuccess: 'Đã chuyển bộ thẻ về trạng thái nháp.',
    archiveSuccess: 'Đã lưu trữ bộ thẻ.',
    crudErrorFallback: 'Thao tác với bộ thẻ thất bại. Vui lòng thử lại.',
    reorderSuccess: 'Đã cập nhật thứ tự thành công.',
    createFolderSuccess: 'Đã tạo thư mục mới.',
    updateFolderSuccess: 'Đã cập nhật thư mục.',
    deleteFolderSuccess: 'Đã xóa thư mục.',
    addCardSuccess: 'Đã thêm thẻ vào thư mục.',
    removeCardSuccess: 'Đã gỡ thẻ khỏi thư mục.',
    searchPublishedOnlyHint: 'Hiện chỉ tìm được các thẻ đã phát hành để thêm vào bộ thẻ.',
  },
  editor: {
    createPageTitle: 'Tạo bộ thẻ mới',
    editPageTitle: 'Chỉnh sửa bộ thẻ',
    createDescription: 'Tạo metadata trước, sau đó chuyển sang màn hình chỉnh sửa để quản lý thư mục và thẻ.',
    editDescription: 'Cập nhật metadata, quản lý thư mục, thêm thẻ và đổi trạng thái phát hành.',
    backToListLabel: 'Quay lại danh sách bộ thẻ',
    detailNotFoundLabel: 'Không tìm thấy dữ liệu bộ thẻ.',
    foldersTitle: 'Thư mục trong bộ thẻ',
    foldersDescription: 'Tổ chức các thẻ học theo nhóm nội dung để người học dễ theo dõi.',
    addFolderLabel: 'Tạo thư mục',
    addCardLabel: 'Thêm thẻ',
    metadataTitleCreate: 'Tạo bộ thẻ',
    metadataTitleEdit: 'Thông tin bộ thẻ',
    formDescription: 'Điền thông tin hiển thị, trạng thái và loại bộ thẻ cho admin.',
    titleLabel: 'Tiêu đề bộ thẻ',
    titlePlaceholder: 'Ví dụ: JLPT N5 Core Vocabulary',
    descriptionLabel: 'Mô tả',
    descriptionPlaceholder: 'Mô tả ngắn về mục tiêu học tập hoặc phạm vi của bộ thẻ này.',
    coverLabel: 'Ảnh bìa',
    coverHint: 'Có thể tải ảnh lên rồi dùng URL trả về để lưu metadata bộ thẻ.',
    typeLabel: 'Loại bộ thẻ',
    typePlaceholder: 'Chọn loại bộ thẻ',
    typeEmptyLabel: 'Chưa phân loại',
    visibilityLabel: 'Hiển thị',
    privateVisibilityTitle: 'Riêng tư',
    privateVisibilityDescription: 'Chỉ user có quyền phù hợp mới truy cập được bộ thẻ này.',
    publicVisibilityTitle: 'Công khai',
    publicVisibilityDescription: 'Có thể được hiển thị cho user khi bộ thẻ ở trạng thái phát hành.',
    statusLabel: 'Trạng thái',
    officialLabel: 'Bộ thẻ hệ thống',
    officialDescription: 'Bật tùy chọn này khi đây là bộ thẻ do hệ thống vận hành hoặc biên tập chính thức.',
    officialBadgeLabel: 'Hệ thống',
    regularBadgeLabel: 'Thường',
    saveCreateLabel: 'Tạo bộ thẻ',
    saveUpdateLabel: 'Lưu thay đổi',
    cancelLabel: 'Hủy',
    creatorLabel: 'Người tạo',
    cardsLabel: 'Số thẻ',
    foldersLabel: 'Số thư mục',
    bookmarksLabel: 'Bookmark',
    updatedAtLabel: 'Cập nhật',
    statusActionLabel: 'Thao tác trạng thái',
    searchCardsPlaceholder: 'Lọc thẻ trong bộ...',
    emptyFoldersLabel: 'Bộ thẻ này chưa có thư mục nào.',
    moveUpLabel: 'Đưa lên',
    moveDownLabel: 'Đưa xuống',
  },
  folderForm: {
    createTitle: 'Tạo thư mục',
    editTitle: 'Chỉnh sửa thư mục',
    titleLabel: 'Tên thư mục',
    titlePlaceholder: 'Ví dụ: Bài 1',
    descriptionLabel: 'Mô tả thư mục',
    descriptionPlaceholder: 'Ghi chú ngắn cho thư mục này.',
    helperDescription: 'Điền tên và mô tả ngắn cho thư mục trong bộ thẻ.',
    submitLabel: 'Lưu thư mục',
    cancelLabel: 'Hủy',
  },
  folder: {
    cardsCountLabel: (count: number) => `${count} thẻ`,
    emptyCardsLabel: 'Thư mục này chưa có thẻ nào.',
    openLabel: 'Mở thư mục',
    closeLabel: 'Thu gọn thư mục',
    editLabel: 'Sửa thư mục',
    deleteLabel: 'Xóa thư mục',
    addCardLabel: 'Thêm thẻ',
    moveUpLabel: 'Đưa thư mục lên',
    moveDownLabel: 'Đưa thư mục xuống',
    removeCardLabel: 'Gỡ thẻ khỏi thư mục',
    openCardLabel: 'Mở card',
  },
  addCardDialog: {
    title: 'Thêm thẻ vào thư mục',
    description: 'Tìm card đã phát hành để thêm vào thư mục hiện tại.',
    searchPlaceholder: 'Tìm tiêu đề, tóm tắt hoặc alternate forms...',
    typeFilterPlaceholder: 'Loại thẻ',
    emptySearchLabel: 'Nhập từ khóa để tìm thẻ.',
    emptyResultLabel: 'Không tìm thấy thẻ phù hợp.',
    publishedHintLabel: 'Admin v1 hiện dùng nguồn search Published.',
    closeLabel: 'Đóng',
    addLabel: 'Thêm vào thư mục',
    addedLabel: 'Đã có trong bộ',
    allCardTypesLabel: 'Tất cả',
  },
  deckTypePage: {
    pageTitle: 'Quản lý loại bộ thẻ',
    heading: 'Quản lý loại bộ thẻ',
    description: 'Tạo, đổi tên và xóa loại bộ thẻ dùng cho toàn bộ hệ thống.',
    searchPlaceholder: 'Tìm theo tên loại bộ thẻ...',
    createLabel: 'Tạo loại mới',
    tableTitle: 'Danh sách loại bộ thẻ',
    emptyTitle: 'Chưa có loại bộ thẻ nào',
    emptyDescription: 'Hãy tạo loại đầu tiên để dùng trong bộ lọc và form bộ thẻ.',
    emptyActionLabel: 'Tạo loại mới',
    columns: {
      name: 'Tên loại',
      createdAt: 'Tạo lúc',
      actions: 'Thao tác',
    },
    editLabel: 'Đổi tên',
    deleteLabel: 'Xóa',
    dialogCreateTitle: 'Tạo loại bộ thẻ',
    dialogEditTitle: 'Đổi tên loại bộ thẻ',
    dialogDescription: 'Tên loại bộ thẻ phải duy nhất trong hệ thống.',
    inputLabel: 'Tên loại bộ thẻ',
    inputPlaceholder: 'Ví dụ: Kanji by Radical',
    submitCreateLabel: 'Tạo loại',
    submitEditLabel: 'Lưu thay đổi',
    cancelLabel: 'Hủy',
    confirmDeleteTitle: 'Xóa loại bộ thẻ?',
    confirmDeleteDescription: 'Nếu loại này còn đang được dùng bởi bộ thẻ khác, backend sẽ từ chối thao tác này.',
    confirmDeleteAction: 'Xóa loại',
    toast: {
      createSuccess: 'Đã tạo loại bộ thẻ thành công.',
      updateSuccess: 'Đã cập nhật loại bộ thẻ thành công.',
      deleteSuccess: 'Đã xóa loại bộ thẻ thành công.',
      crudErrorFallback: 'Thao tác với loại bộ thẻ thất bại. Vui lòng thử lại.',
    },
  },
} as const
