export const ADMIN_SENTENCE_CONTENT = {
	pageTitle: 'Quản lý câu ví dụ',
	heading: 'Quản lý câu ví dụ',
	description: 'Tra cứu, tạo mới, chỉnh sửa và xóa dữ liệu câu ví dụ từ backend.',
	searchPlaceholder: 'Tìm theo nội dung hoặc nghĩa...',
	filterButtonLabel: 'Bộ lọc',
	filterTitle: 'Bộ lọc câu ví dụ',
	filterDescription: 'Tùy chỉnh bộ lọc nâng cao để thu hẹp kết quả danh sách.',
	activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
	activeKeywordLabel: 'Từ khóa',
	activeLevelLabel: 'Cấp độ',
	activeHasAudioLabel: 'Audio',
	activeCreatedByMeLabel: 'Người tạo',
	activeCreatedByMeValue: 'Chỉ của tôi',
	resultCountLabel: (count: number) => `${count} kết quả`,
	applyFilterLabel: 'Áp dụng bộ lọc',
	levelLabel: 'Cấp độ JLPT',
	createdByMeLabel: 'Chỉ của tôi',
	hasAudioLabel: 'Tình trạng audio',
	hasAudioYesLabel: 'Có audio',
	hasAudioNoLabel: 'Không audio',
	clearFilterLabel: 'Xóa lọc',
	searchLabel: 'Tìm kiếm',
	createLabel: 'Tạo câu mới',
	tableTitle: 'Danh sách câu ví dụ',
	emptyTitle: 'Chưa có câu ví dụ nào phù hợp',
	emptyDescription: 'Thử đổi từ khóa hoặc bỏ bộ lọc cấp độ để xem dữ liệu.',
	emptyActionLabel: 'Tạo câu mới',
	columns: {
		text: 'Câu tiếng Nhật',
		level: 'Cấp độ',
		createdAt: 'Tạo lúc',
		updatedAt: 'Cập nhật',
		actions: 'Thao tác',
	},
	audioPlayLabel: 'Phát audio',
	audioPauseLabel: 'Dừng audio',
	actions: {
		edit: 'Sửa',
		delete: 'Xóa',
		confirmDelete: 'Bạn có chắc chắn muốn xóa câu ví dụ này?',
		downloadTemplate: 'Tải mẫu JSON',
		exportJson: 'Xuất JSON',
		importJson: 'Import JSON',
	},
	toast: {
		createSuccess: 'Đã tạo câu ví dụ thành công.',
		updateSuccess: 'Đã cập nhật câu ví dụ thành công.',
		deleteSuccess: 'Đã xóa câu ví dụ thành công.',
		crudErrorFallback: 'Thao tác thất bại. Vui lòng thử lại.',
		downloadTemplateSuccess: 'Đã tải mẫu import sentence.',
		exportSuccess: 'Đã tải file export sentence.',
		importCommitSuccess: 'Đã commit import sentence thành công.',
		importInvalidJson: 'Tệp JSON không đúng định dạng import sentence.',
		importReadFailed: 'Không đọc được tệp JSON. Vui lòng kiểm tra lại.',
		importPreviewError: 'Không thể preview import sentence.',
		importCommitError: 'Không thể commit import sentence.',
	},
	form: {
		createTitle: 'Tạo câu ví dụ mới',
		editTitle: 'Chỉnh sửa câu ví dụ',
		description: 'Điền thông tin và chọn giọng VOICEVOX để backend tự generate audio.',
		dialogTitleCreate: 'Tạo câu ví dụ mới',
		dialogTitleEdit: 'Chỉnh sửa câu ví dụ',
		dialogDescription: 'Biểu mẫu thao tác câu ví dụ trong quản trị nội dung.',
		createActionLabel: 'Lưu mới',
		updateActionLabel: 'Lưu cập nhật',
		cancelActionLabel: 'Hủy',
		generatePreviewLabel: 'Tạo audio preview',
		audioPreviewLabel: 'Audio phát âm hiện tại',
		audioEmptyLabel: 'Chưa có audio cho câu này',
		speakerRequiredLabel: 'Vui lòng chọn speaker trước khi tạo/cập nhật câu ví dụ.',
		previewAudioSuccessLabel: 'Đã tạo audio preview thành công.',
		previewAudioFailedLabel: 'Không thể tạo audio preview. Vui lòng thử lại.',
		playAudioLabel: 'Phát audio',
		playAudioFailedLabel: 'Không thể phát audio. Vui lòng kiểm tra lại tệp.',
		fields: {
			textLabel: 'Câu tiếng Nhật',
			textPlaceholder: 'Ví dụ: 毎朝パンを食べます。',
			meaningLabel: 'Nghĩa tiếng Việt',
			meaningPlaceholder: 'Ví dụ: Mỗi sáng tôi ăn bánh mì.',
			speakerLabel: 'Speaker VOICEVOX',
			speakerPlaceholder: 'Chọn giọng đọc',
			levelLabel: 'Cấp độ JLPT',
		},
	},
	importDialog: {
		title: 'Import câu ví dụ từ JSON',
		description: 'Chọn tệp JSON, preview dữ liệu và commit batch import sentence.',
		fileLabel: 'Tệp JSON import',
		fileHint: 'Chỉ hỗ trợ tệp .json theo mẫu import sentence.',
		previewButtonLabel: 'Preview import',
		commitButtonLabel: 'Commit import',
		closeButtonLabel: 'Đóng',
		selectedFileLabel: 'Tệp đã chọn',
		summaryTitle: 'Tổng quan preview',
		totalItemsLabel: 'Tổng item',
		validItemsLabel: 'Hợp lệ',
		invalidItemsLabel: 'Không hợp lệ',
		emptyPreviewLabel: 'Chưa có dữ liệu preview. Hãy chọn file và bấm Preview import.',
		hasInvalidBlockLabel: 'Có item không hợp lệ, vui lòng chỉnh file rồi preview lại trước khi commit.',
		resultTitle: 'Kết quả preview theo từng dòng',
		columns: {
			rowNumber: 'Dòng',
			text: 'Nội dung',
			status: 'Trạng thái',
			errors: 'Lỗi',
			warnings: 'Cảnh báo',
		},
		statusValidLabel: 'Hợp lệ',
		statusInvalidLabel: 'Không hợp lệ',
	},
	previousPageLabel: 'Trang trước',
	nextPageLabel: 'Trang sau',
} as const

export const ADMIN_VOCABULARY_CONTENT = {
	pageTitle: 'Quản lý từ vựng',
	heading: 'Quản lý từ vựng',
	description: 'Theo dõi danh sách thẻ từ vựng và kiểm tra trạng thái dữ liệu từ backend.',
	searchPlaceholder: 'Tìm theo từ vựng hoặc cách đọc...',
	filterButtonLabel: 'Bộ lọc',
	filterTitle: 'Bộ lọc từ vựng',
	filterDescription: 'Tùy chỉnh bộ lọc nâng cao để thu hẹp kết quả danh sách.',
	activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
	activeKeywordLabel: 'Từ khóa',
	activeLevelLabel: 'Cấp độ',
	activeStatusLabel: 'Trạng thái',
	activeWordTypeLabel: 'Loại từ',
	activeHasAudioLabel: 'Audio',
	activeCreatedByMeLabel: 'Người tạo',
	activeCreatedByMeValue: 'Chỉ của tôi',
	activeEnabledLabel: 'Đang bật',
	resultCountLabel: (count: number) => `${count} kết quả`,
	applyFilterLabel: 'Áp dụng bộ lọc',
	levelLabel: 'Cấp độ JLPT',
	statusLabel: 'Trạng thái',
	wordTypeLabel: 'Loại từ',
	hasAudioLabel: 'Tình trạng audio',
	hasAudioYesLabel: 'Có audio',
	hasAudioNoLabel: 'Không audio',
	createdByMeLabel: 'Chỉ của tôi',
	clearFilterLabel: 'Xóa lọc',
	searchLabel: 'Tìm kiếm',
	createLabel: 'Tạo từ vựng mới',
	backToListLabel: 'Quay lại quản lý từ vựng',
	tableTitle: 'Danh sách thẻ từ vựng',
	emptyTitle: 'Không có thẻ từ vựng phù hợp',
	emptyDescription: 'Thử đổi từ khóa hoặc điều chỉnh bộ lọc trạng thái.',
	emptyActionLabel: 'Tạo từ vựng mới',
	summaryFallbackLabel: 'Chưa có tóm tắt',
	tagsCountLabel: (count: number) => `${count} tag`,
	columns: {
		title: 'Từ vựng',
		wordType: 'Loại từ',
		level: 'Cấp độ',
		tags: 'Tag',
		status: 'Trạng thái',
		createdAt: 'Tạo lúc',
		updatedAt: 'Cập nhật',
		actions: 'Thao tác',
	},
	audioPlayLabel: 'Phát audio',
	audioPauseLabel: 'Dừng audio',
	actions: {
		edit: 'Sửa',
		delete: 'Xóa',
		confirmDelete: 'Bạn có chắc chắn muốn xóa từ vựng này?',
		saveDraft: 'Lưu bản nháp',
		downloadTemplate: 'Tải mẫu JSON',
		exportJson: 'Xuất JSON',
		importJson: 'Import JSON',
	},
	editor: {
		createPageTitle: 'Tạo từ vựng mới',
		editPageTitle: 'Chỉnh sửa từ vựng',
		createDescription: 'Nhập đầy đủ thông tin để tạo một thẻ từ vựng mới.',
		editDescription: 'Cập nhật nội dung từ vựng và lưu thay đổi.',
		notFoundLabel: 'Không tìm thấy dữ liệu từ vựng.',
		confirmLeaveTitle: 'Bạn chưa lưu thay đổi',
		confirmLeaveDescription: 'Bạn muốn hủy form này và rời trang, hay ở lại để tiếp tục chỉnh sửa?',
		confirmLeaveDiscardLabel: 'Hủy form và rời trang',
		confirmLeaveStayLabel: 'Ở lại chỉnh sửa',
	},
	toast: {
		createSuccess: 'Đã tạo từ vựng thành công.',
		updateSuccess: 'Đã cập nhật từ vựng thành công.',
		deleteSuccess: 'Đã xóa từ vựng thành công.',
		crudErrorFallback: 'Thao tác thất bại. Vui lòng thử lại.',
		downloadTemplateSuccess: 'Đã tải mẫu import vocabulary.',
		exportSuccess: 'Đã tải file export vocabulary.',
		importCommitSuccess: 'Đã commit import vocabulary thành công.',
		importInvalidJson: 'Tệp JSON không đúng định dạng import vocabulary.',
		importReadFailed: 'Không đọc được tệp JSON. Vui lòng kiểm tra lại.',
		importPreviewError: 'Không thể preview import vocabulary.',
		importCommitError: 'Không thể commit import vocabulary.',
	},
	form: {
		dialogTitleCreate: 'Tạo từ vựng mới',
		dialogTitleEdit: 'Chỉnh sửa từ vựng',
		dialogDescription: 'Biểu mẫu thao tác từ vựng trong quản trị nội dung.',
		sections: {
			basicTitle: 'Thông tin cơ bản',
			meaningsTitle: 'Nghĩa và định nghĩa',
			relationsTitle: 'Từ liên quan',
			sentencesTitle: 'Câu ví dụ',
			audioTitle: 'Audio phát âm',
			meaningItemLabel: (index: number) => `Nghĩa #${index}`,
			sentenceItemLabel: (index: number) => `Câu ví dụ #${index}`,
		},
		loadingDetailLabel: 'Đang tải chi tiết từ vựng...',
		createActionLabel: 'Lưu mới',
		updateActionLabel: 'Lưu cập nhật',
		cancelActionLabel: 'Hủy',
		uploadAudioLabel: 'Tải audio lên',
		recordAudioLabel: 'Ghi âm',
		stopRecordLabel: 'Dừng ghi',
		removeAudioLabel: 'Bỏ audio',
		generatePreviewLabel: 'Tạo audio preview',
		removePreviewLabel: 'Xóa preview',
		audioPreviewLabel: 'Audio phát âm hiện tại',
		audioEmptyLabel: 'Chưa có audio cho từ vựng này',
		playAudioFailedLabel: 'Không thể phát audio. Vui lòng kiểm tra lại tệp.',
		audioFileHintLabel: 'Hỗ trợ: MP3 (.mp3), WAV (.wav), M4A (.m4a).',
		uploadingAudioLabel: 'Đang tải audio lên...',
		recordNotSupportedLabel: 'Trình duyệt chưa hỗ trợ ghi âm.',
		recordNotAllowedLabel: 'Không thể truy cập micro. Hãy cấp quyền rồi thử lại.',
		uploadAudioSuccess: 'Đã tải audio lên thành công.',
		uploadAudioFailed: 'Tải audio lên thất bại. Vui lòng thử lại.',
		speakerRequiredLabel: 'Vui lòng chọn speaker VOICEVOX trước khi lưu.',
		previewAudioSuccessLabel: 'Đã tạo audio preview thành công.',
		previewAudioFailedLabel: 'Không thể tạo audio preview. Vui lòng thử lại.',
		searchSentenceLibraryLabel: 'Tìm thư viện',
		searchSentenceLibraryFailedLabel: 'Không thể tìm câu ví dụ trong thư viện.',
		addSentenceLabel: 'Thêm câu mới',
		addSentenceFromLibraryLabel: 'Thêm vào card',
		removeSentenceLabel: 'Xóa câu',
		sentenceLibraryTitle: 'Thêm từ thư viện câu ví dụ',
		sentenceLibraryPlaceholder: 'Nhập từ khóa câu ví dụ...',
		sentencesEmptyLabel: 'Chưa có câu ví dụ nào cho card này.',
		addMeaningLabel: 'Thêm nghĩa',
		removeMeaningLabel: 'Xóa nghĩa',
		addDefinitionLabel: 'Thêm nghĩa nhỏ',
		removeDefinitionLabel: 'Xóa',
		addItemLabel: 'Thêm',
		removeItemLabel: 'Xóa',
		clearPitchPatternLabel: 'Đặt lại pitch',
		pitchPatternLabel: 'Ngữ điệu (Pitch)',
		pitchPatternDescriptionLabel: 'Click âm tiết để đổi cao ↔ thấp.',
		pitchPatternEmptyLabel: 'Chưa có mốc cao độ nào.',
		pitchPatternHighLabel: 'Cao',
		pitchPatternLowLabel: 'Thấp',
		audioFormatHintAriaLabel: 'Định dạng audio được hỗ trợ',
		pitchPresetFlatLowLabel: 'Thấp đều',
		pitchPresetFlatHighLabel: 'Cao đều',
		pitchPresetRiseLabel: 'Tăng dần',
		pitchPresetFallLabel: 'Giảm dần',
		pitchContourLabel: 'Đường ngữ điệu',
		fields: {
			titleLabel: 'Tiêu đề',
			titlePlaceholder: 'Ví dụ: 食べる',
			summaryLabel: 'Tóm tắt',
			summaryPlaceholder: 'Mô tả ngắn về từ vựng',
			readingLabel: 'Cách đọc',
			readingPlaceholder: 'Ví dụ: たべる',
			levelLabel: 'Cấp độ JLPT',
			statusLabel: 'Trạng thái',
			wordTypeLabel: 'Loại từ',
			wordTypePlaceholder: 'Chọn loại từ',
			tagsLabel: 'Tags',
			tagsPlaceholder: 'Nhập tag rồi nhấn Enter',
			meaningPartOfSpeechLabel: 'Từ loại',
			meaningPartOfSpeechPlaceholder: 'Chọn từ loại',
			meaningDefinitionsLabel: 'Danh sách nghĩa',
			meaningDefinitionsPlaceholder: 'Nhập nghĩa rồi nhấn Enter',
			synonymsLabel: 'Từ đồng nghĩa',
			synonymsPlaceholder: 'Nhập từ đồng nghĩa rồi nhấn Enter',
			antonymsLabel: 'Từ trái nghĩa',
			antonymsPlaceholder: 'Nhập từ trái nghĩa rồi nhấn Enter',
			relatedPhrasesLabel: 'Cụm liên quan',
			relatedPhrasesPlaceholder: 'Nhập cụm liên quan rồi nhấn Enter',
			audioFileLabel: 'Tệp audio',
			speakerLabel: 'Speaker VOICEVOX',
			speakerPlaceholder: 'Chọn giọng đọc',
			sentenceTextLabel: 'Câu ví dụ',
			sentenceTextPlaceholder: 'Ví dụ: 毎朝パンを食べる。',
			sentenceMeaningLabel: 'Nghĩa câu ví dụ',
			sentenceMeaningPlaceholder: 'Ví dụ: Mỗi sáng tôi ăn bánh mì.',
			sentenceLevelLabel: 'Cấp độ câu ví dụ',
			sentenceSpeakerLabel: 'Speaker câu ví dụ',
			sentenceSpeakerPlaceholder: 'Dùng speaker mặc định của card',
		},
	},
	importDialog: {
		title: 'Import từ vựng từ JSON',
		description: 'Chọn tệp JSON, preview dữ liệu và commit batch import vocabulary.',
		fileLabel: 'Tệp JSON import',
		fileHint: 'Chỉ hỗ trợ tệp .json theo mẫu import vocabulary.',
		previewButtonLabel: 'Preview import',
		commitButtonLabel: 'Commit import',
		closeButtonLabel: 'Đóng',
		selectedFileLabel: 'Tệp đã chọn',
		summaryTitle: 'Tổng quan preview',
		totalItemsLabel: 'Tổng item',
		validItemsLabel: 'Hợp lệ',
		invalidItemsLabel: 'Không hợp lệ',
		emptyPreviewLabel: 'Chưa có dữ liệu preview. Hãy chọn file và bấm Preview import.',
		hasInvalidBlockLabel: 'Có item không hợp lệ, vui lòng chỉnh file rồi preview lại trước khi commit.',
		resultTitle: 'Kết quả preview theo từng dòng',
		columns: {
			rowNumber: 'Dòng',
			title: 'Tiêu đề',
			writing: 'Writing',
			status: 'Trạng thái',
			errors: 'Lỗi',
			warnings: 'Cảnh báo',
		},
		statusValidLabel: 'Hợp lệ',
		statusInvalidLabel: 'Không hợp lệ',
	},
	previousPageLabel: 'Trang trước',
	nextPageLabel: 'Trang sau',
} as const

export const ADMIN_COMMON_CONTENT = {
	loadingLabel: 'Đang tải dữ liệu...',
	apiErrorFallback: 'Không tải được dữ liệu. Vui lòng thử lại.',
	pageInfoLabel: (page: number, total: number) => `Trang ${page} / ${total}`,
	notUpdatedLabel: 'Chưa cập nhật',
	emptyValueLabel: 'Chưa có',
	createActionLabel: 'Tạo mới',
	importErrorFallbackLabel: 'Có lỗi dữ liệu trong file import.',
	importWarningFallbackLabel: 'Có cảnh báo dữ liệu trong file import.',
	importErrorUnknownFieldLabel: (fieldPath: string) => `Dữ liệu không hợp lệ tại trường ${fieldPath}.`,
	importErrorByCode: {
		Sentence_ImportFieldRequired_400: 'Thiếu trường bắt buộc.',
		Sentence_ImportFieldTooLong_400: 'Giá trị vượt quá độ dài cho phép.',
		Sentence_ImportFieldInvalid_400: 'Giá trị không hợp lệ.',
		Sentence_ImportSpeakerIdNotSupported_400: 'Speaker không được hỗ trợ.',
		Vocabulary_ImportFieldRequired_400: 'Thiếu trường bắt buộc.',
		Vocabulary_ImportFieldTooLong_400: 'Giá trị vượt quá độ dài cho phép.',
		Vocabulary_ImportFieldInvalid_400: 'Giá trị không hợp lệ.',
		Vocabulary_ImportSentenceIdNotAllowed_400: 'Không được gửi sentence id trong import create-only.',
		Vocabulary_ImportDuplicateWritingInBatch_400: 'Trùng writing trong cùng batch import.',
		Vocabulary_ImportWritingAlreadyExists_400: 'Writing đã tồn tại trong hệ thống.',
	},
} as const
