export const ADMIN_USER_CONTENT = {
  pageTitle: 'Quản lý người dùng | Tacho Admin',
  heading: 'Quản lý người dùng',
  description: 'Xem, phân quyền, khóa/mở khóa và quản lý tài khoản người dùng.',
  searchPlaceholder: 'Tìm theo email hoặc tên hiển thị...',
  filterButtonLabel: 'Bộ lọc',
  filterTitle: 'Bộ lọc người dùng',
  filterDescription: 'Tùy chỉnh bộ lọc để thu hẹp kết quả danh sách.',
  activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
  activeKeywordLabel: 'Từ khóa',
  activeRoleLabel: 'Vai trò',
  activeStatusLabel: 'Trạng thái',
  activeVerificationLabel: 'Xác minh',
  activeIsActiveLabel: 'Hoạt động',
  activeIsInactiveLabel: 'Bị khóa',
  activeIsVerifiedLabel: 'Đã xác minh',
  activeIsNotVerifiedLabel: 'Chưa xác minh',
  resultCountLabel: (count: number) => `${count} kết quả`,
  applyFilterLabel: 'Áp dụng bộ lọc',
  roleLabel: 'Vai trò',
  statusLabel: 'Trạng thái hoạt động',
  isActiveLabel: 'Hoạt động',
  isInactiveLabel: 'Bị khóa',
  isVerifiedLabel: 'Đã xác minh',
  isNotVerifiedLabel: 'Chưa xác minh',
  isVerifiedFilterLabel: 'Trạng thái xác minh',
  clearFilterLabel: 'Xóa lọc',
  searchLabel: 'Tìm kiếm',
  tableTitle: 'Danh sách người dùng',
  emptyTitle: 'Không có người dùng phù hợp',
  emptyDescription: 'Thử đổi từ khóa hoặc bỏ bộ lọc.',
  emptyActionLabel: undefined,
  columns: {
    user: 'Người dùng',
    email: 'Email',
    displayName: 'Tên hiển thị',
    role: 'Vai trò',
    status: 'Trạng thái',
    verified: 'Xác minh',
    createdAt: 'Ngày tạo',
    updatedAt: 'Cập nhật',
    actions: 'Thao tác',
  },
  actions: {
    viewDetail: 'Xem chi tiết',
    changeRole: 'Đổi vai trò',
    toggleStatus: 'Khóa/Mở khóa',
    toggleVerification: 'Xác minh/Tắt xác minh',
    sendResetPassword: 'Gửi email đặt lại mật khẩu',
    confirmDeactivate: 'Bạn có chắc chắn muốn khóa tài khoản này?',
    confirmActivate: 'Bạn có chắc chắn muốn mở khóa tài khoản này?',
  },
  dialogs: {
    changeRole: {
      title: 'Đổi vai trò người dùng',
      description: 'Chọn vai trò mới cho người dùng. Người dùng sẽ cần đăng nhập lại sau khi đổi vai trò.',
      currentRoleLabel: 'Vai trò hiện tại',
      newRoleLabel: 'Vai trò mới',
      confirmLabel: 'Xác nhận đổi vai trò',
      cancelLabel: 'Hủy',
      success: 'Đã đổi vai trò thành công.',
    },
    changeStatus: {
      deactivate: {
        title: 'Khóa tài khoản',
        description: 'Tài khoản này sẽ bị khóa và người dùng không thể đăng nhập. Tất cả refresh token hiện tại sẽ bị thu hồi.',
        confirmLabel: 'Khóa tài khoản',
      },
      activate: {
        title: 'Mở khóa tài khoản',
        description: 'Tài khoản sẽ được kích hoạt trở lại và người dùng có thể đăng nhập như bình thường.',
        confirmLabel: 'Mở khóa tài khoản',
      },
      cancelLabel: 'Hủy',
      successDeactivate: 'Đã khóa tài khoản thành công.',
      successActivate: 'Đã mở khóa tài khoản thành công.',
    },
    changeVerification: {
      verify: {
        title: 'Xác minh tài khoản',
        description: 'Tài khoản sẽ được đánh dấu là đã xác minh.',
        confirmLabel: 'Xác minh tài khoản',
      },
      unverify: {
        title: 'Hủy xác minh tài khoản',
        description: 'Tài khoản sẽ bị hủy trạng thái đã xác minh.',
        confirmLabel: 'Hủy xác minh',
      },
      cancelLabel: 'Hủy',
      successVerify: 'Đã xác minh tài khoản thành công.',
      successUnverify: 'Đã hủy xác minh tài khoản thành công.',
    },
    sendResetPassword: {
      title: 'Gửi email đặt lại mật khẩu',
      description: 'Hệ thống sẽ gửi email đặt lại mật khẩu đến địa chỉ của người dùng.',
      confirmLabel: 'Gửi email',
      cancelLabel: 'Hủy',
      success: 'Đã gửi email đặt lại mật khẩu thành công.',
      failed: 'Không thể gửi email đặt lại mật khẩu.',
    },
  },
  toast: {
    crudErrorFallback: 'Thao tác thất bại. Vui lòng thử lại.',
  },
  previousPageLabel: 'Trang trước',
  nextPageLabel: 'Trang sau',
} as const