export const ADMIN_SENTENCE_CONTENT = {
	pageTitle: 'Quản lý câu ví dụ',
	heading: 'Quản lý câu ví dụ',
	description: 'Tra cứu, tạo mới, chỉnh sửa và xóa dữ liệu câu ví dụ từ backend.',
	searchPlaceholder: 'Tìm theo nội dung hoặc nghĩa...',
	filterButtonLabel: 'Bộ lọc',
	filterTitle: 'Bộ lọc câu ví dụ',
	filterDescription: 'Tùy chỉnh bộ lọc nâng cao để thu hẹp kết quả danh sách.',
	activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
	activeKeywordLabel: 'Từ khóa',
	activeLevelLabel: 'Cấp độ',
	resultCountLabel: (count: number) => `${count} kết quả`,
	applyFilterLabel: 'Áp dụng bộ lọc',
	levelLabel: 'Cấp độ JLPT',
	clearFilterLabel: 'Xóa lọc',
	searchLabel: 'Tìm kiếm',
	createLabel: 'Tạo câu mới',
	tableTitle: 'Danh sách câu ví dụ',
	emptyTitle: 'Chưa có câu ví dụ nào phù hợp',
	emptyDescription: 'Thử đổi từ khóa hoặc bỏ bộ lọc cấp độ để xem dữ liệu.',
	columns: {
		text: 'Câu tiếng Nhật',
		meaning: 'Nghĩa tiếng Việt',
		level: 'Cấp độ',
		updatedAt: 'Cập nhật',
		actions: 'Thao tác',
	},
	actions: {
		edit: 'Sửa',
		delete: 'Xóa',
		confirmDelete: 'Bạn có chắc chắn muốn xóa câu ví dụ này?',
	},
	toast: {
		createSuccess: 'Đã tạo câu ví dụ thành công.',
		updateSuccess: 'Đã cập nhật câu ví dụ thành công.',
		deleteSuccess: 'Đã xóa câu ví dụ thành công.',
		crudErrorFallback: 'Thao tác thất bại. Vui lòng thử lại.',
	},
	form: {
		createTitle: 'Tạo câu ví dụ mới',
		editTitle: 'Chỉnh sửa câu ví dụ',
		description: 'Điền thông tin và chọn audio phát âm cho câu ví dụ.',
		dialogTitleCreate: 'Tạo câu ví dụ mới',
		dialogTitleEdit: 'Chỉnh sửa câu ví dụ',
		dialogDescription: 'Biểu mẫu thao tác câu ví dụ trong quản trị nội dung.',
		createActionLabel: 'Lưu mới',
		updateActionLabel: 'Lưu cập nhật',
		cancelActionLabel: 'Hủy',
		uploadAudioLabel: 'Tải audio lên',
		recordAudioLabel: 'Ghi âm',
		stopRecordLabel: 'Dừng ghi',
		removeAudioLabel: 'Bỏ audio',
		audioPreviewLabel: 'Audio phát âm hiện tại',
		audioEmptyLabel: 'Chưa có audio cho câu này',
		uploadingAudioLabel: 'Đang tải audio lên...',
		recordNotSupportedLabel: 'Trình duyệt chưa hỗ trợ ghi âm.',
		recordNotAllowedLabel: 'Không thể truy cập micro. Hãy cấp quyền rồi thử lại.',
		uploadAudioSuccess: 'Đã tải audio lên thành công.',
		uploadAudioFailed: 'Tải audio lên thất bại. Vui lòng thử lại.',
		playAudioLabel: 'Phát audio',
		playAudioFailedLabel: 'Không thể phát audio. Vui lòng kiểm tra lại tệp.',
		fields: {
			textLabel: 'Câu tiếng Nhật',
			textPlaceholder: 'Ví dụ: 毎朝パンを食べます。',
			meaningLabel: 'Nghĩa tiếng Việt',
			meaningPlaceholder: 'Ví dụ: Mỗi sáng tôi ăn bánh mì.',
			audioFileLabel: 'Tệp audio',
			audioFileHintLabel: 'Hỗ trợ: MP3 (.mp3), WAV (.wav), M4A (.m4a).',
			levelLabel: 'Cấp độ JLPT',
		},
	},
	previousPageLabel: 'Trang trước',
	nextPageLabel: 'Trang sau',
} as const

export const ADMIN_VOCABULARY_CONTENT = {
	pageTitle: 'Quản lý từ vựng',
	heading: 'Quản lý từ vựng',
	description: 'Theo dõi danh sách thẻ từ vựng và kiểm tra trạng thái dữ liệu từ backend.',
	searchPlaceholder: 'Tìm theo từ vựng hoặc cách đọc...',
	filterButtonLabel: 'Bộ lọc',
	filterTitle: 'Bộ lọc từ vựng',
	filterDescription: 'Tùy chỉnh bộ lọc nâng cao để thu hẹp kết quả danh sách.',
	activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
	activeKeywordLabel: 'Từ khóa',
	activeLevelLabel: 'Cấp độ',
	activeStatusLabel: 'Trạng thái',
	activeCreatedByMeLabel: 'Người tạo',
	activeCreatedByMeValue: 'Chỉ của tôi',
	activeEnabledLabel: 'Đang bật',
	resultCountLabel: (count: number) => `${count} kết quả`,
	applyFilterLabel: 'Áp dụng bộ lọc',
	levelLabel: 'Cấp độ JLPT',
	statusLabel: 'Trạng thái',
	createdByMeLabel: 'Chỉ của tôi',
	clearFilterLabel: 'Xóa lọc',
	searchLabel: 'Tìm kiếm',
	createLabel: 'Tạo từ vựng mới',
	tableTitle: 'Danh sách thẻ từ vựng',
	emptyTitle: 'Không có thẻ từ vựng phù hợp',
	emptyDescription: 'Thử đổi từ khóa hoặc điều chỉnh bộ lọc trạng thái.',
	columns: {
		title: 'Từ vựng',
		level: 'Cấp độ',
		status: 'Trạng thái',
		updatedAt: 'Cập nhật',
		actions: 'Thao tác',
	},
	actions: {
		edit: 'Sửa',
		delete: 'Xóa',
		confirmDelete: 'Bạn có chắc chắn muốn xóa từ vựng này?',
	},
	toast: {
		createSuccess: 'Đã tạo từ vựng thành công.',
		updateSuccess: 'Đã cập nhật từ vựng thành công.',
		deleteSuccess: 'Đã xóa từ vựng thành công.',
		crudErrorFallback: 'Thao tác thất bại. Vui lòng thử lại.',
	},
	form: {
		dialogTitleCreate: 'Tạo từ vựng mới',
		dialogTitleEdit: 'Chỉnh sửa từ vựng',
		dialogDescription: 'Biểu mẫu thao tác từ vựng trong quản trị nội dung.',
		loadingDetailLabel: 'Đang tải chi tiết từ vựng...',
		createActionLabel: 'Lưu mới',
		updateActionLabel: 'Lưu cập nhật',
		cancelActionLabel: 'Hủy',
		uploadAudioLabel: 'Tải audio lên',
		recordAudioLabel: 'Ghi âm',
		stopRecordLabel: 'Dừng ghi',
		removeAudioLabel: 'Bỏ audio',
		audioPreviewLabel: 'Audio phát âm hiện tại',
		audioEmptyLabel: 'Chưa có audio cho từ vựng này',
		audioFileHintLabel: 'Hỗ trợ: MP3 (.mp3), WAV (.wav), M4A (.m4a).',
		uploadingAudioLabel: 'Đang tải audio lên...',
		recordNotSupportedLabel: 'Trình duyệt chưa hỗ trợ ghi âm.',
		recordNotAllowedLabel: 'Không thể truy cập micro. Hãy cấp quyền rồi thử lại.',
		uploadAudioSuccess: 'Đã tải audio lên thành công.',
		uploadAudioFailed: 'Tải audio lên thất bại. Vui lòng thử lại.',
		addMeaningLabel: 'Thêm nghĩa',
		removeMeaningLabel: 'Xóa nghĩa',
		addDefinitionLabel: 'Thêm nghĩa nhỏ',
		removeDefinitionLabel: 'Xóa',
		addItemLabel: 'Thêm',
		removeItemLabel: 'Xóa',
		clearPitchPatternLabel: 'Đặt lại pitch',
		pitchPatternLabel: 'Ngữ điệu (Pitch)',
		pitchPatternDescriptionLabel: 'Click âm tiết để đổi cao ↔ thấp.',
		pitchPatternEmptyLabel: 'Chưa có mốc cao độ nào.',
		pitchPatternHighLabel: 'Cao',
		pitchPatternLowLabel: 'Thấp',
		pitchPresetFlatLowLabel: 'Thấp đều',
		pitchPresetFlatHighLabel: 'Cao đều',
		pitchPresetRiseLabel: 'Tăng dần',
		pitchPresetFallLabel: 'Giảm dần',
		pitchContourLabel: 'Đường ngữ điệu',
		fields: {
			titleLabel: 'Tiêu đề',
			titlePlaceholder: 'Ví dụ: 食べる',
			summaryLabel: 'Tóm tắt',
			summaryPlaceholder: 'Mô tả ngắn về từ vựng',
			readingLabel: 'Cách đọc',
			readingPlaceholder: 'Ví dụ: たべる',
			levelLabel: 'Cấp độ JLPT',
			statusLabel: 'Trạng thái',
			wordTypeLabel: 'Loại từ',
			wordTypePlaceholder: 'Chọn loại từ',
			tagsLabel: 'Tags',
			tagsPlaceholder: 'Nhập tag rồi nhấn Enter',
			meaningPartOfSpeechLabel: 'Từ loại',
			meaningPartOfSpeechPlaceholder: 'Chọn từ loại',
			meaningDefinitionsLabel: 'Danh sách nghĩa',
			meaningDefinitionsPlaceholder: 'Nhập nghĩa rồi nhấn Enter',
			synonymsLabel: 'Từ đồng nghĩa',
			synonymsPlaceholder: 'Nhập từ đồng nghĩa rồi nhấn Enter',
			antonymsLabel: 'Từ trái nghĩa',
			antonymsPlaceholder: 'Nhập từ trái nghĩa rồi nhấn Enter',
			relatedPhrasesLabel: 'Cụm liên quan',
			relatedPhrasesPlaceholder: 'Nhập cụm liên quan rồi nhấn Enter',
			audioFileLabel: 'Tệp audio',
		},
	},
	previousPageLabel: 'Trang trước',
	nextPageLabel: 'Trang sau',
} as const

export const ADMIN_COMMON_CONTENT = {
	loadingLabel: 'Đang tải dữ liệu...',
	apiErrorFallback: 'Không tải được dữ liệu. Vui lòng thử lại.',
	pageInfoLabel: (page: number, total: number) => `Trang ${page} / ${total}`,
	notUpdatedLabel: 'Chưa cập nhật',
} as const
