export const ADMIN_LEARNING_CONTENT = {
	overview: {
		pageTitle: 'Tổng quan học tập | Tacho Admin',
		heading: 'Tổng quan học tập',
		description: 'Số liệu tổng hợp hoạt động học tập trong ngày.',
		activeUsersTodayLabel: 'Người dùng hôm nay',
		sessionsTodayLabel: 'Phiên học hôm nay',
		completedSessionsTodayLabel: 'Phiên hoàn thành',
		submissionsTodayLabel: 'Lượt nộp bài',
		dueCardsNowLabel: 'Thẻ cần ôn',
		averageAccuracyLabel: 'Độ chính xác TB',
		accuracySuffix: '%',
	},
	issues: {
		pageTitle: 'Vấn đề nội dung học tập | Tacho Admin',
		heading: 'Vấn đề nội dung học tập',
		description: 'Danh sách thẻ có lỗi cấu hình ảnh hưởng đến chế độ học.',
		searchPlaceholder: 'Tìm theo tiêu đề hoặc tóm tắt thẻ...',
		filterButtonLabel: 'Bộ lọc',
		filterTitle: 'Bộ lọc vấn đề',
		filterDescription: 'Lọc theo loại thẻ, chế độ học hoặc loại vấn đề.',
		cardTypeLabel: 'Loại thẻ',
		modeLabel: 'Chế độ học',
		issueTypeLabel: 'Loại vấn đề',
		deckLabel: 'Bộ thẻ',
		deckPlaceholder: 'Chọn bộ thẻ',
		clearFilterLabel: 'Xóa lọc',
		applyFilterLabel: 'Áp dụng bộ lọc',
		resultCountLabel: (count: number) => `${count} kết quả`,
		tableTitle: 'Thẻ có vấn đề nội dung',
		columns: {
			title: 'Tiêu đề',
			cardType: 'Loại thẻ',
			summary: 'Tóm tắt',
			availableModes: 'Chế độ sẵn sàng',
			issues: 'Vấn đề',
			actions: 'Thao tác',
		},
		emptyTitle: 'Không tìm thấy vấn đề nào',
		emptyDescription: 'Tất cả thẻ đều đã sẵn sàng cho chế độ học, hoặc thử điều chỉnh bộ lọc.',
		previousPageLabel: 'Trang trước',
		nextPageLabel: 'Trang sau',
		actions: {
			viewConfig: 'Xem cấu hình',
			viewAnalytics: 'Xem phân tích',
		},
	},
	coverage: {
		pageTitle: 'Độ phủ học tập | Tacho Admin',
		heading: 'Độ phủ học tập',
		description: 'Thống kê mức độ sẵn sàng cho từng chế độ học.',
		backToDecksLabel: 'Quay lại danh sách bộ thẻ',
		totalCardsLabel: 'Tổng số thẻ',
		fillInBlankReadyLabel: 'Sẵn sàng điền chỗ trống',
		multipleChoiceReadyLabel: 'Sẵn sàng trắc nghiệm',
		flashcardReadyLabel: 'Sẵn sàng flashcard',
		issueCountLabel: 'Thẻ có vấn đề',
		breakdownTitle: 'Chi tiết theo loại thẻ',
		breakdownColumns: {
			cardType: 'Loại thẻ',
			total: 'Tổng',
			fillInBlank: 'Điền chỗ trống',
			multipleChoice: 'Trắc nghiệm',
			flashcard: 'Flashcard',
		},
		viewIssuesLabel: 'Xem danh sách vấn đề',
		notFoundLabel: 'Không tìm thấy dữ liệu bộ thẻ.',
	},
	cardConfig: {
		drawerTitle: 'Cấu hình học tập',
		drawerDescription: 'Chỉnh sửa tóm tắt và câu ví dụ cho chế độ học.',
		detailDescription: (title: string, cardType: string) => `${title} • ${cardType}`,
		summaryLabel: 'Tóm tắt (Summary)',
		summaryPlaceholder: 'Nhập tóm tắt cho thẻ...',
		sentencesTitle: 'Câu ví dụ gắn liền',
		sentencesEmptyLabel: 'Chưa có câu ví dụ nào được gắn.',
		sentencesCountLabel: (count: number) => `${count} câu ví dụ`,
		addSentenceLabel: 'Thêm câu ví dụ',
		removeSentenceLabel: 'Gỡ câu ví dụ',
		saveConfigLabel: 'Lưu cấu hình',
		cancelLabel: 'Hủy',
		readinessTitle: 'Mức độ sẵn sàng',
		issuesTitle: 'Vấn đề phát hiện',
		issueCountLabel: (count: number) => `${count} vấn đề`,
		noIssuesLabel: 'Không có vấn đề nào.',
		issuesSectionDescription: 'Các cảnh báo cần xử lý để mở đầy đủ chế độ học.',
		issueSentenceIdLabel: (sentenceId: string) => `Mã câu: ${sentenceId}`,
		positionLabel: 'Vị trí',
		blankWordLabel: 'Từ trống (blankWord)',
		blankWordPlaceholder: 'Nhập từ cần ẩn...',
		hintLabel: 'Gợi ý (hint)',
		hintPlaceholder: 'Nhập gợi ý cho người học...',
		answerListLabel: 'Danh sách đáp án',
		answerListPlaceholder: 'Nhập đáp án rồi nhấn Enter',
		dragHintLabel: 'Kéo để thay đổi thứ tự',
		previewLabel: 'Xem trước bài tập',
	},
	sentencePicker: {
		title: 'Thêm câu ví dụ từ thư viện',
		description: 'Tìm và chọn câu để gắn vào thẻ học tập.',
		searchPlaceholder: 'Nhập từ khóa tìm câu ví dụ...',
		emptyLabel: 'Không tìm thấy câu ví dụ phù hợp.',
		attachLabel: 'Gắn vào thẻ',
		cancelLabel: 'Hủy',
	},
	preview: {
		title: 'Xem trước bài tập',
		description: 'Xem nội dung bài tập được tạo cho thẻ này.',
		configTitle: 'Thiết lập xem trước',
		contentTitle: 'Nội dung hiển thị',
		previewPromptLabel: 'Nhắc người học',
		modeLabel: 'Chế độ học',
		questionLabel: 'Câu hỏi',
		secondaryLabel: 'Phụ đề',
		hintLabel: 'Gợi ý',
		frontLabel: 'Mặt trước',
		backLabel: 'Mặt sau',
		optionsLabel: 'Đáp án',
		correctBadge: 'Đúng',
		incorrectBadge: 'Sai',
		warningsLabel: 'Cảnh báo',
		noWarningsLabel: 'Không có cảnh báo.',
		closeLabel: 'Đóng',
		mcQuestionLabel: 'Kiểu câu hỏi MC',
		flashcardFrontLabel: 'Mặt trước FC',
		flashcardBackLabel: 'Mặt sau FC',
		shuffleLabel: 'Xáo trộn đáp án',
		noDataLabel: 'Chưa có dữ liệu xem trước cho cấu hình hiện tại.',
	},
	analytics: {
		deckTitle: 'Phân tích bộ thẻ',
		deckDescription: 'Thống kê phiên học và tiến độ theo bộ thẻ.',
		cardTitle: 'Phân tích thẻ',
		cardDescription: 'Thống kê sử dụng và SRS cho thẻ này.',
		userTitle: 'Tiến độ người dùng',
		userDescription: 'Tổng quan quá trình học tập của người dùng.',
		sessionCountLabel: 'Tổng phiên học',
		completedSessionCountLabel: 'Phiên hoàn thành',
		submissionCountLabel: 'Lượt nộp bài',
		averageAccuracyLabel: 'Độ chính xác TB',
		trackedCardsLabel: 'Thẻ đã theo dõi',
		masteredCardsLabel: 'Thẻ đã thuần thục',
		dueCardsLabel: 'Thẻ cần ôn',
		trackedUsersLabel: 'Người dùng theo dõi',
		masteredUsersLabel: 'Người dùng thuần thục',
		dueUsersLabel: 'Người dùng cần ôn',
		averageSrsLevelLabel: 'SRS TB',
		averageConsecutiveCorrectLabel: 'Streak đúng TB',
		lastReviewedAtLabel: 'Ôn gần nhất',
		neverReviewedLabel: 'Chưa ôn',
		modeBreakdownTitle: 'Phân tích theo chế độ',
		modeBreakdownColumns: {
			mode: 'Chế độ',
			sessions: 'Phiên',
			completed: 'Hoàn thành',
			submissions: 'Nộp bài',
			accuracy: 'Chính xác',
		},
		srsDistributionTitle: 'Phân bố SRS',
		srsDistributionColumns: {
			level: 'Cấp SRS',
			count: 'Số lượng',
		},
		deckUsageTitle: 'Bộ thẻ sử dụng',
		recentSessionCountLabel: 'Phiên gần đây',
		closeLabel: 'Đóng',
		summaryLabel: 'Tóm tắt thẻ',
		noDeckUsageLabel: 'Thẻ này chưa phát sinh dữ liệu sử dụng theo bộ thẻ.',
		srsDistributionHint: 'Số người dùng theo từng cấp SRS.',
	},
	toast: {
		configSaveSuccess: 'Đã lưu cấu hình học tập.',
		configSaveError: 'Không thể lưu cấu hình. Vui lòng thử lại.',
		attachSentenceSuccess: 'Đã gắn câu ví dụ vào thẻ.',
		attachSentenceError: 'Không thể gắn câu ví dụ. Vui lòng thử lại.',
		removeSentenceSuccess: 'Đã gỡ câu ví dụ khỏi thẻ.',
		removeSentenceError: 'Không thể gỡ câu ví dụ. Vui lòng thử lại.',
		reorderSuccess: 'Đã cập nhật thứ tự câu.',
		reorderError: 'Không thể cập nhật thứ tự. Vui lòng thử lại.',
		loadError: 'Không tải được dữ liệu. Vui lòng thử lại.',
	},
	errorCodes: {
		Learning_CardNotFound_404: 'Thẻ không tồn tại.',
		Learning_SentenceNotAttached_404: 'Câu chưa được gắn với thẻ này.',
		Learning_SentenceAlreadyAttached_400: 'Câu đã được gắn với thẻ này.',
		Sentence_NotFound_404: 'Câu ví dụ không tồn tại.',
	} as Record<string, string>,
} as const
