export const ADMIN_SENTENCE_CONTENT = {
	pageTitle: 'Quản lý câu ví dụ',
	heading: 'Quản lý câu ví dụ',
	description: 'Tra cứu, tạo mới, chỉnh sửa và xóa dữ liệu câu ví dụ từ backend.',
	searchPlaceholder: 'Tìm theo nội dung hoặc nghĩa...',
	filterButtonLabel: 'Bộ lọc',
	filterTitle: 'Bộ lọc câu ví dụ',
	filterDescription: 'Tùy chỉnh bộ lọc nâng cao để thu hẹp kết quả danh sách.',
	activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
	activeKeywordLabel: 'Từ khóa',
	activeLevelLabel: 'Cấp độ',
	activeHasAudioLabel: 'Audio',
	activeCreatedByMeLabel: 'Người tạo',
	activeCreatedByMeValue: 'Chỉ của tôi',
	resultCountLabel: (count: number) => `${count} kết quả`,
	applyFilterLabel: 'Áp dụng bộ lọc',
	levelLabel: 'Cấp độ JLPT',
	createdByMeLabel: 'Chỉ của tôi',
	hasAudioLabel: 'Tình trạng audio',
	hasAudioYesLabel: 'Có audio',
	hasAudioNoLabel: 'Không audio',
	clearFilterLabel: 'Xóa lọc',
	searchLabel: 'Tìm kiếm',
	createLabel: 'Tạo câu mới',
	tableTitle: 'Danh sách câu ví dụ',
	emptyTitle: 'Chưa có câu ví dụ nào phù hợp',
	emptyDescription: 'Thử đổi từ khóa hoặc bỏ bộ lọc cấp độ để xem dữ liệu.',
	emptyActionLabel: 'Tạo câu mới',
	columns: {
		text: 'Câu tiếng Nhật',
		level: 'Cấp độ',
		createdAt: 'Tạo lúc',
		updatedAt: 'Cập nhật',
		actions: 'Thao tác',
	},
	audioPlayLabel: 'Phát audio',
	audioPauseLabel: 'Dừng audio',
	actions: {
		edit: 'Sửa',
		delete: 'Xóa',
		confirmDelete: 'Bạn có chắc chắn muốn xóa câu ví dụ này?',
		downloadTemplate: 'Tải mẫu JSON',
		exportJson: 'Xuất JSON',
		importJson: 'Import JSON',
	},
	toast: {
		createSuccess: 'Đã tạo câu ví dụ thành công.',
		updateSuccess: 'Đã cập nhật câu ví dụ thành công.',
		deleteSuccess: 'Đã xóa câu ví dụ thành công.',
		crudErrorFallback: 'Thao tác thất bại. Vui lòng thử lại.',
		downloadTemplateSuccess: 'Đã tải mẫu import sentence.',
		exportSuccess: 'Đã tải file export sentence.',
		importCommitSuccess: 'Đã commit import sentence thành công.',
		importInvalidJson: 'Tệp JSON không đúng định dạng import sentence.',
		importReadFailed: 'Không đọc được tệp JSON. Vui lòng kiểm tra lại.',
		importPreviewError: 'Không thể preview import sentence.',
		importCommitError: 'Không thể commit import sentence.',
	},
	form: {
		createTitle: 'Tạo câu ví dụ mới',
		editTitle: 'Chỉnh sửa câu ví dụ',
		description: 'Điền thông tin và chọn giọng VOICEVOX để backend tự generate audio.',
		dialogTitleCreate: 'Tạo câu ví dụ mới',
		dialogTitleEdit: 'Chỉnh sửa câu ví dụ',
		dialogDescription: 'Biểu mẫu thao tác câu ví dụ trong quản trị nội dung.',
		createActionLabel: 'Lưu mới',
		updateActionLabel: 'Lưu cập nhật',
		cancelActionLabel: 'Hủy',
		generatePreviewLabel: 'Tạo audio preview',
		audioPreviewLabel: 'Audio phát âm hiện tại',
		audioEmptyLabel: 'Chưa có audio cho câu này',
		speakerRequiredLabel: 'Vui lòng chọn speaker trước khi tạo/cập nhật câu ví dụ.',
		previewAudioSuccessLabel: 'Đã tạo audio preview thành công.',
		previewAudioFailedLabel: 'Không thể tạo audio preview. Vui lòng thử lại.',
		playAudioLabel: 'Phát audio',
		playAudioFailedLabel: 'Không thể phát audio. Vui lòng kiểm tra lại tệp.',
		fields: {
			textLabel: 'Câu tiếng Nhật',
			textPlaceholder: 'Ví dụ: 毎朝パンを食べます。',
			meaningLabel: 'Nghĩa tiếng Việt',
			meaningPlaceholder: 'Ví dụ: Mỗi sáng tôi ăn bánh mì.',
			speakerLabel: 'Speaker VOICEVOX',
			speakerPlaceholder: 'Chọn giọng đọc',
			levelLabel: 'Cấp độ JLPT',
		},
	},
	importDialog: {
		title: 'Import câu ví dụ từ JSON',
		description: 'Chọn tệp JSON, preview dữ liệu và commit batch import sentence.',
		fileLabel: 'Tệp JSON import',
		fileHint: 'Chỉ hỗ trợ tệp .json theo mẫu import sentence.',
		previewButtonLabel: 'Preview import',
		commitButtonLabel: 'Commit import',
		closeButtonLabel: 'Đóng',
		selectedFileLabel: 'Tệp đã chọn',
		summaryTitle: 'Tổng quan preview',
		totalItemsLabel: 'Tổng item',
		validItemsLabel: 'Hợp lệ',
		invalidItemsLabel: 'Không hợp lệ',
		emptyPreviewLabel: 'Chưa có dữ liệu preview. Hãy chọn file và bấm Preview import.',
		hasInvalidBlockLabel: 'Có item không hợp lệ, vui lòng chỉnh file rồi preview lại trước khi commit.',
		resultTitle: 'Kết quả preview theo từng dòng',
		columns: {
			rowNumber: 'Dòng',
			text: 'Nội dung',
			status: 'Trạng thái',
			errors: 'Lỗi',
			warnings: 'Cảnh báo',
		},
		statusValidLabel: 'Hợp lệ',
		statusInvalidLabel: 'Không hợp lệ',
	},
	previousPageLabel: 'Trang trước',
	nextPageLabel: 'Trang sau',
} as const

export const ADMIN_VOCABULARY_CONTENT = {
	pageTitle: 'Quản lý từ vựng',
	heading: 'Quản lý từ vựng',
	description: 'Theo dõi danh sách thẻ từ vựng và kiểm tra trạng thái dữ liệu từ backend.',
	searchPlaceholder: 'Tìm theo từ vựng hoặc cách đọc...',
	filterButtonLabel: 'Bộ lọc',
	filterTitle: 'Bộ lọc từ vựng',
	filterDescription: 'Tùy chỉnh bộ lọc nâng cao để thu hẹp kết quả danh sách.',
	activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
	activeKeywordLabel: 'Từ khóa',
	activeLevelLabel: 'Cấp độ',
	activeStatusLabel: 'Trạng thái',
	activeWordTypeLabel: 'Loại từ',
	activeHasAudioLabel: 'Audio',
	activeCreatedByMeLabel: 'Người tạo',
	activeCreatedByMeValue: 'Chỉ của tôi',
	activeEnabledLabel: 'Đang bật',
	resultCountLabel: (count: number) => `${count} kết quả`,
	applyFilterLabel: 'Áp dụng bộ lọc',
	levelLabel: 'Cấp độ JLPT',
	statusLabel: 'Trạng thái',
	wordTypeLabel: 'Loại từ',
	hasAudioLabel: 'Tình trạng audio',
	hasAudioYesLabel: 'Có audio',
	hasAudioNoLabel: 'Không audio',
	createdByMeLabel: 'Chỉ của tôi',
	clearFilterLabel: 'Xóa lọc',
	searchLabel: 'Tìm kiếm',
	createLabel: 'Tạo từ vựng mới',
	backToListLabel: 'Quay lại quản lý từ vựng',
	tableTitle: 'Danh sách thẻ từ vựng',
	emptyTitle: 'Không có thẻ từ vựng phù hợp',
	emptyDescription: 'Thử đổi từ khóa hoặc điều chỉnh bộ lọc trạng thái.',
	emptyActionLabel: 'Tạo từ vựng mới',
	summaryFallbackLabel: 'Chưa có tóm tắt',
	tagsCountLabel: (count: number) => `${count} tag`,
	columns: {
		title: 'Từ vựng',
		wordType: 'Loại từ',
		level: 'Cấp độ',
		tags: 'Tag',
		status: 'Trạng thái',
		createdAt: 'Tạo lúc',
		updatedAt: 'Cập nhật',
		actions: 'Thao tác',
	},
	audioPlayLabel: 'Phát audio',
	audioPauseLabel: 'Dừng audio',
	actions: {
		edit: 'Sửa',
		delete: 'Xóa',
		confirmDelete: 'Bạn có chắc chắn muốn xóa từ vựng này?',
		saveDraft: 'Lưu bản nháp',
		downloadTemplate: 'Tải mẫu JSON',
		exportJson: 'Xuất JSON',
		importJson: 'Import JSON',
	},
	editor: {
		createPageTitle: 'Tạo từ vựng mới',
		editPageTitle: 'Chỉnh sửa từ vựng',
		createDescription: 'Nhập đầy đủ thông tin để tạo một thẻ từ vựng mới.',
		editDescription: 'Cập nhật nội dung từ vựng và lưu thay đổi.',
		notFoundLabel: 'Không tìm thấy dữ liệu từ vựng.',
		confirmLeaveTitle: 'Bạn chưa lưu thay đổi',
		confirmLeaveDescription: 'Bạn muốn hủy form này và rời trang, hay ở lại để tiếp tục chỉnh sửa?',
		confirmLeaveDiscardLabel: 'Hủy form và rời trang',
		confirmLeaveStayLabel: 'Ở lại chỉnh sửa',
	},
	toast: {
		createSuccess: 'Đã tạo từ vựng thành công.',
		updateSuccess: 'Đã cập nhật từ vựng thành công.',
		deleteSuccess: 'Đã xóa từ vựng thành công.',
		crudErrorFallback: 'Thao tác thất bại. Vui lòng thử lại.',
		downloadTemplateSuccess: 'Đã tải mẫu import vocabulary.',
		exportSuccess: 'Đã tải file export vocabulary.',
		importCommitSuccess: 'Đã commit import vocabulary thành công.',
		importInvalidJson: 'Tệp JSON không đúng định dạng import vocabulary.',
		importReadFailed: 'Không đọc được tệp JSON. Vui lòng kiểm tra lại.',
		importPreviewError: 'Không thể preview import vocabulary.',
		importCommitError: 'Không thể commit import vocabulary.',
	},
	form: {
		dialogTitleCreate: 'Tạo từ vựng mới',
		dialogTitleEdit: 'Chỉnh sửa từ vựng',
		dialogDescription: 'Biểu mẫu thao tác từ vựng trong quản trị nội dung.',
		sections: {
			basicTitle: 'Thông tin cơ bản',
			meaningsTitle: 'Nghĩa và định nghĩa',
			relationsTitle: 'Từ liên quan',
			sentencesTitle: 'Câu ví dụ',
			audioTitle: 'Audio phát âm',
			meaningItemLabel: (index: number) => `Nghĩa #${index}`,
			sentenceItemLabel: (index: number) => `Câu ví dụ #${index}`,
		},
		loadingDetailLabel: 'Đang tải chi tiết từ vựng...',
		createActionLabel: 'Lưu mới',
		updateActionLabel: 'Lưu cập nhật',
		cancelActionLabel: 'Hủy',
		uploadAudioLabel: 'Tải audio lên',
		recordAudioLabel: 'Ghi âm',
		stopRecordLabel: 'Dừng ghi',
		removeAudioLabel: 'Bỏ audio',
		generatePreviewLabel: 'Tạo audio preview',
		removePreviewLabel: 'Xóa preview',
		audioPreviewLabel: 'Audio phát âm hiện tại',
		audioEmptyLabel: 'Chưa có audio cho từ vựng này',
		playAudioFailedLabel: 'Không thể phát audio. Vui lòng kiểm tra lại tệp.',
		audioFileHintLabel: 'Hỗ trợ: MP3 (.mp3), WAV (.wav), M4A (.m4a).',
		uploadingAudioLabel: 'Đang tải audio lên...',
		recordNotSupportedLabel: 'Trình duyệt chưa hỗ trợ ghi âm.',
		recordNotAllowedLabel: 'Không thể truy cập micro. Hãy cấp quyền rồi thử lại.',
		uploadAudioSuccess: 'Đã tải audio lên thành công.',
		uploadAudioFailed: 'Tải audio lên thất bại. Vui lòng thử lại.',
		speakerRequiredLabel: 'Vui lòng chọn speaker VOICEVOX trước khi lưu.',
		previewAudioSuccessLabel: 'Đã tạo audio preview thành công.',
		previewAudioFailedLabel: 'Không thể tạo audio preview. Vui lòng thử lại.',
		searchSentenceLibraryLabel: 'Tìm thư viện',
		searchSentenceLibraryFailedLabel: 'Không thể tìm câu ví dụ trong thư viện.',
		addSentenceLabel: 'Thêm câu mới',
		addSentenceFromLibraryLabel: 'Thêm vào card',
		removeSentenceLabel: 'Xóa câu',
		sentenceLibraryTitle: 'Thêm từ thư viện câu ví dụ',
		sentenceLibraryPlaceholder: 'Nhập từ khóa câu ví dụ...',
		sentencesEmptyLabel: 'Chưa có câu ví dụ nào cho card này.',
		addMeaningLabel: 'Thêm nghĩa',
		removeMeaningLabel: 'Xóa nghĩa',
		addDefinitionLabel: 'Thêm nghĩa nhỏ',
		removeDefinitionLabel: 'Xóa',
		addItemLabel: 'Thêm',
		removeItemLabel: 'Xóa',
		clearPitchPatternLabel: 'Đặt lại pitch',
		pitchPatternLabel: 'Ngữ điệu (Pitch)',
		pitchPatternDescriptionLabel: 'Click âm tiết để đổi cao ↔ thấp.',
		pitchPatternEmptyLabel: 'Chưa có mốc cao độ nào.',
		pitchPatternHighLabel: 'Cao',
		pitchPatternLowLabel: 'Thấp',
		audioFormatHintAriaLabel: 'Định dạng audio được hỗ trợ',
		pitchPresetFlatLowLabel: 'Thấp đều',
		pitchPresetFlatHighLabel: 'Cao đều',
		pitchPresetRiseLabel: 'Tăng dần',
		pitchPresetFallLabel: 'Giảm dần',
		pitchContourLabel: 'Đường ngữ điệu',
		fields: {
			titleLabel: 'Tiêu đề',
			titlePlaceholder: 'Ví dụ: 食べる',
			summaryLabel: 'Tóm tắt',
			summaryPlaceholder: 'Mô tả ngắn về từ vựng',
			readingLabel: 'Cách đọc',
			readingPlaceholder: 'Ví dụ: たべる',
			levelLabel: 'Cấp độ JLPT',
			statusLabel: 'Trạng thái',
			wordTypeLabel: 'Loại từ',
			wordTypePlaceholder: 'Chọn loại từ',
			tagsLabel: 'Tags',
			tagsPlaceholder: 'Nhập tag rồi nhấn Enter',
			meaningPartOfSpeechLabel: 'Từ loại',
			meaningPartOfSpeechPlaceholder: 'Chọn từ loại',
			meaningDefinitionsLabel: 'Danh sách nghĩa',
			meaningDefinitionsPlaceholder: 'Nhập nghĩa rồi nhấn Enter',
			synonymsLabel: 'Từ đồng nghĩa',
			synonymsPlaceholder: 'Nhập từ đồng nghĩa rồi nhấn Enter',
			antonymsLabel: 'Từ trái nghĩa',
			antonymsPlaceholder: 'Nhập từ trái nghĩa rồi nhấn Enter',
			relatedPhrasesLabel: 'Cụm liên quan',
			relatedPhrasesPlaceholder: 'Nhập cụm liên quan rồi nhấn Enter',
			audioFileLabel: 'Tệp audio',
			speakerLabel: 'Speaker VOICEVOX',
			speakerPlaceholder: 'Chọn giọng đọc',
			sentenceTextLabel: 'Câu ví dụ',
			sentenceTextPlaceholder: 'Ví dụ: 毎朝パンを食べる。',
			sentenceMeaningLabel: 'Nghĩa câu ví dụ',
			sentenceMeaningPlaceholder: 'Ví dụ: Mỗi sáng tôi ăn bánh mì.',
			sentenceLevelLabel: 'Cấp độ câu ví dụ',
			sentenceSpeakerLabel: 'Speaker câu ví dụ',
			sentenceSpeakerPlaceholder: 'Dùng speaker mặc định của card',
		},
	},
	importDialog: {
		title: 'Import từ vựng từ JSON',
		description: 'Chọn tệp JSON, preview dữ liệu và commit batch import vocabulary.',
		fileLabel: 'Tệp JSON import',
		fileHint: 'Chỉ hỗ trợ tệp .json theo mẫu import vocabulary.',
		previewButtonLabel: 'Preview import',
		commitButtonLabel: 'Commit import',
		closeButtonLabel: 'Đóng',
		selectedFileLabel: 'Tệp đã chọn',
		summaryTitle: 'Tổng quan preview',
		totalItemsLabel: 'Tổng item',
		validItemsLabel: 'Hợp lệ',
		invalidItemsLabel: 'Không hợp lệ',
		emptyPreviewLabel: 'Chưa có dữ liệu preview. Hãy chọn file và bấm Preview import.',
		hasInvalidBlockLabel: 'Có item không hợp lệ, vui lòng chỉnh file rồi preview lại trước khi commit.',
		resultTitle: 'Kết quả preview theo từng dòng',
		columns: {
			rowNumber: 'Dòng',
			title: 'Tiêu đề',
			writing: 'Writing',
			status: 'Trạng thái',
			errors: 'Lỗi',
			warnings: 'Cảnh báo',
		},
		statusValidLabel: 'Hợp lệ',
		statusInvalidLabel: 'Không hợp lệ',
	},
	previousPageLabel: 'Trang trước',
	nextPageLabel: 'Trang sau',
} as const

export const ADMIN_GRAMMAR_CONTENT = {
	pageTitle: 'Quản lý ngữ pháp',
	heading: 'Quản lý ngữ pháp',
	description: 'Theo dõi danh sách thẻ ngữ pháp và kiểm tra trạng thái dữ liệu từ backend.',
	searchPlaceholder: 'Tìm theo tiêu đề hoặc tóm tắt ngữ pháp...',
	filterButtonLabel: 'Bộ lọc',
	filterTitle: 'Bộ lọc ngữ pháp',
	filterDescription: 'Tùy chỉnh bộ lọc nâng cao để thu hẹp kết quả danh sách.',
	activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
	activeKeywordLabel: 'Từ khóa',
	activeLevelLabel: 'Cấp độ',
	activeStatusLabel: 'Trạng thái',
	activeRegisterLabel: 'Ngữ cảnh',
	activeCreatedByMeLabel: 'Người tạo',
	activeCreatedByMeValue: 'Chỉ của tôi',
	activeEnabledLabel: 'Đang bật',
	resultCountLabel: (count: number) => `${count} kết quả`,
	applyFilterLabel: 'Áp dụng bộ lọc',
	levelLabel: 'Cấp độ JLPT',
	statusLabel: 'Trạng thái',
	registerLabel: 'Ngữ cảnh sử dụng',
	createdByMeLabel: 'Chỉ của tôi',
	clearFilterLabel: 'Xóa lọc',
	searchLabel: 'Tìm kiếm',
	createLabel: 'Tạo ngữ pháp mới',
	backToListLabel: 'Quay lại quản lý ngữ pháp',
	tableTitle: 'Danh sách thẻ ngữ pháp',
	emptyTitle: 'Không có thẻ ngữ pháp phù hợp',
	emptyDescription: 'Thử đổi từ khóa hoặc điều chỉnh bộ lọc trạng thái.',
	emptyActionLabel: 'Tạo ngữ pháp mới',
	summaryFallbackLabel: 'Chưa có tóm tắt',
	tagsCountLabel: (count: number) => `${count} tag`,
	structuresCountLabel: (count: number) => `${count} cấu trúc`,
	columns: {
		title: 'Ngữ pháp',
		register: 'Ngữ cảnh',
		level: 'Cấp độ',
		structures: 'Cấu trúc',
		alternateForms: 'Dạng thay thế',
		status: 'Trạng thái',
		createdAt: 'Tạo lúc',
		updatedAt: 'Cập nhật',
		actions: 'Thao tác',
	},
	actions: {
		edit: 'Sửa',
		delete: 'Xóa',
		confirmDelete: 'Bạn có chắc chắn muốn xóa ngữ pháp này?',
		saveDraft: 'Lưu bản nháp',
		downloadTemplate: 'Tải mẫu JSON',
		exportJson: 'Xuất JSON',
		importJson: 'Import JSON',
	},
	editor: {
		createPageTitle: 'Tạo ngữ pháp mới',
		editPageTitle: 'Chỉnh sửa ngữ pháp',
		createDescription: 'Nhập đầy đủ thông tin để tạo một thẻ ngữ pháp mới.',
		editDescription: 'Cập nhật nội dung ngữ pháp và lưu thay đổi.',
		notFoundLabel: 'Không tìm thấy dữ liệu ngữ pháp.',
		confirmLeaveTitle: 'Bạn chưa lưu thay đổi',
		confirmLeaveDescription: 'Bạn muốn hủy form này và rời trang, hay ở lại để tiếp tục chỉnh sửa?',
		confirmLeaveDiscardLabel: 'Hủy form và rời trang',
		confirmLeaveStayLabel: 'Ở lại chỉnh sửa',
	},
	toast: {
		createSuccess: 'Đã tạo ngữ pháp thành công.',
		updateSuccess: 'Đã cập nhật ngữ pháp thành công.',
		deleteSuccess: 'Đã xóa ngữ pháp thành công.',
		crudErrorFallback: 'Thao tác thất bại. Vui lòng thử lại.',
		downloadTemplateSuccess: 'Đã tải mẫu import grammar.',
		exportSuccess: 'Đã tải file export grammar.',
		importCommitSuccess: 'Đã commit import grammar thành công.',
		importInvalidJson: 'Tệp JSON không đúng định dạng import grammar.',
		importReadFailed: 'Không đọc được tệp JSON. Vui lòng kiểm tra lại.',
		importPreviewError: 'Không thể preview import grammar.',
		importCommitError: 'Không thể commit import grammar.',
	},
	form: {
		dialogTitleCreate: 'Tạo ngữ pháp mới',
		dialogTitleEdit: 'Chỉnh sửa ngữ pháp',
		dialogDescription: 'Biểu mẫu thao tác ngữ pháp trong quản trị nội dung.',
		loadingDetailLabel: 'Đang tải chi tiết ngữ pháp...',
		createActionLabel: 'Lưu mới',
		updateActionLabel: 'Lưu cập nhật',
		cancelActionLabel: 'Hủy',
		searchSentenceLibraryLabel: 'Tìm thư viện',
		searchSentenceLibraryFailedLabel: 'Không thể tìm câu ví dụ trong thư viện.',
		addSentenceLabel: 'Thêm câu mới',
		addSentenceFromLibraryLabel: 'Thêm vào card',
		removeSentenceLabel: 'Xóa câu',
		sentenceLibraryTitle: 'Thêm từ thư viện câu ví dụ',
		sentenceLibraryPlaceholder: 'Nhập từ khóa câu ví dụ...',
		sentencesEmptyLabel: 'Chưa có câu ví dụ nào cho card này.',
		addItemLabel: 'Thêm',
		removeItemLabel: 'Xóa',
		tabs: {
			basic: 'Thông tin cơ bản',
			structures: 'Cấu trúc',
			content: 'Nội dung',
			relations: 'Liên quan',
			sentences: 'Câu ví dụ',
		},
		sections: {
			basicTitle: 'Thông tin cơ bản',
			structuresTitle: 'Cấu trúc ngữ pháp',
			contentTitle: 'Giải thích & Lưu ý',
			relationsTitle: 'Ngữ pháp liên quan',
			resourcesTitle: 'Tài liệu tham khảo',
			sentencesTitle: 'Câu ví dụ',
			structureItemLabel: (index: number) => `Cấu trúc #${index}`,
			sentenceItemLabel: (index: number) => `Câu ví dụ #${index}`,
			relationItemLabel: (index: number) => `Liên quan #${index}`,
			resourceItemLabel: (index: number) => `Tài liệu #${index}`,
		},
		fields: {
			titleLabel: 'Tiêu đề',
			titlePlaceholder: 'Ví dụ: 〜ながら',
			summaryLabel: 'Tóm tắt',
			summaryPlaceholder: 'Mô tả ngắn về ngữ pháp',
			levelLabel: 'Cấp độ JLPT',
			statusLabel: 'Trạng thái',
			registerLabel: 'Ngữ cảnh sử dụng',
			registerPlaceholder: 'Chọn ngữ cảnh',
			tagsLabel: 'Tags',
			tagsPlaceholder: 'Nhập tag rồi nhấn Enter',
			alternateFormsLabel: 'Dạng thay thế',
			alternateFormsPlaceholder: 'Nhập dạng thay thế rồi nhấn Enter',
			patternLabel: 'Mẫu cấu trúc',
			patternPlaceholder: 'Ví dụ: V1(1) + ながら + V2(2)',
			annotationKeyLabel: 'Số thứ tự',
			annotationKeyPlaceholder: 'VD: 1',
			annotationValueLabel: 'Chú thích',
			annotationValuePlaceholder: 'Nhập nội dung chú thích...',
			annotationSelectionHint: 'Bôi đen một phần trong mẫu cấu trúc rồi bấm thêm chú thích. Hệ thống sẽ tự chèn số thứ tự vào pattern.',
			annotationEmptyLabel: 'Chưa có chú thích nào cho cấu trúc này.',
			annotationSelectedTextLabel: 'Neo tại',
			annotationMissingSelectionLabel: 'Hãy bôi đen phần cần chú thích trong mẫu cấu trúc trước.',
			annotationMissingMarkerLabel: 'Marker này không còn trong pattern. Hãy thêm lại chú thích từ đoạn cần neo.',
			explanationLabel: 'Giải thích chi tiết',
			explanationPlaceholder: 'Nhập giải thích chi tiết cho mẫu ngữ pháp...',
			cautionLabel: 'Lưu ý',
			cautionPlaceholder: 'Nhập lưu ý khi sử dụng mẫu ngữ pháp...',
			relatedIdLabel: 'Ngữ pháp liên quan',
			relatedIdPlaceholder: 'Tìm ngữ pháp theo tiêu đề...',
			relationTypeLabel: 'Loại quan hệ',
			resourceTitleLabel: 'Tiêu đề tài liệu',
			resourceTitlePlaceholder: 'VD: Bài giảng',
			resourceUrlLabel: 'URL tài liệu',
			resourceUrlPlaceholder: 'https://example.com/grammar',
			sentenceTextLabel: 'Câu ví dụ',
			sentenceTextPlaceholder: 'Ví dụ: 音楽を聞きながら勉強します。',
			sentenceMeaningLabel: 'Nghĩa câu ví dụ',
			sentenceMeaningPlaceholder: 'Ví dụ: Tôi vừa nghe nhạc vừa học.',
			sentenceLevelLabel: 'Cấp độ câu ví dụ',
			sentenceSpeakerLabel: 'Speaker câu ví dụ',
			sentenceSpeakerPlaceholder: 'Chọn giọng đọc',
		},
		addStructureLabel: 'Thêm cấu trúc',
		removeStructureLabel: 'Xóa cấu trúc',
		addAnnotationLabel: 'Thêm chú thích từ đoạn đang chọn',
		removeAnnotationLabel: 'Xóa chú thích',
		addRelationLabel: 'Thêm ngữ pháp liên quan',
		removeRelationLabel: 'Xóa liên kết',
		addResourceLabel: 'Thêm tài liệu',
		removeResourceLabel: 'Xóa tài liệu',
		richTextHint: 'Hỗ trợ: **in đậm**, *in nghiêng*, ~~gạch ngang~~, {u}gạch chân{/u}, {red}màu{/red}',
		noRelationsLabel: 'Chưa có ngữ pháp liên quan.',
		noResourcesLabel: 'Chưa có tài liệu tham khảo.',
		noStructuresLabel: 'Chưa có cấu trúc nào.',
		searchGrammarNoResultLabel: 'Không tìm thấy ngữ pháp phù hợp.',
		searchGrammarLoadingLabel: 'Đang tìm kiếm...',
	},
	importDialog: {
		title: 'Import ngữ pháp từ JSON',
		description: 'Chọn tệp JSON, preview dữ liệu và commit batch import grammar.',
		fileLabel: 'Tệp JSON import',
		fileHint: 'Chỉ hỗ trợ tệp .json theo mẫu import grammar.',
		previewButtonLabel: 'Preview import',
		commitButtonLabel: 'Commit import',
		closeButtonLabel: 'Đóng',
		selectedFileLabel: 'Tệp đã chọn',
		summaryTitle: 'Tổng quan preview',
		totalItemsLabel: 'Tổng item',
		validItemsLabel: 'Hợp lệ',
		invalidItemsLabel: 'Không hợp lệ',
		emptyPreviewLabel: 'Chưa có dữ liệu preview. Hãy chọn file và bấm Preview import.',
		hasInvalidBlockLabel: 'Có item không hợp lệ, vui lòng chỉnh file rồi preview lại trước khi commit.',
		resultTitle: 'Kết quả preview theo từng dòng',
		columns: {
			rowNumber: 'Dòng',
			title: 'Tiêu đề',
			status: 'Trạng thái',
			errors: 'Lỗi',
			warnings: 'Cảnh báo',
		},
		statusValidLabel: 'Hợp lệ',
		statusInvalidLabel: 'Không hợp lệ',
	},
	previousPageLabel: 'Trang trước',
	nextPageLabel: 'Trang sau',
} as const

export const ADMIN_KANJI_CONTENT = {
	pageTitle: 'Quản lý Hán tự',
	heading: 'Quản lý Hán tự',
	description: 'Theo dõi danh sách thẻ Hán tự và kiểm tra trạng thái dữ liệu từ backend.',
	searchPlaceholder: 'Tìm theo Hán tự, nghĩa, hoặc âm Hán Việt...',
	filterButtonLabel: 'Bộ lọc',
	filterTitle: 'Bộ lọc Hán tự',
	filterDescription: 'Tùy chỉnh bộ lọc nâng cao để thu hẹp kết quả danh sách.',
	activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
	activeKeywordLabel: 'Từ khóa',
	activeLevelLabel: 'Cấp độ',
	activeStatusLabel: 'Trạng thái',
	activeStrokeCountLabel: 'Số nét',
	activeRadicalLabel: 'Bộ thủ',
	activeCreatedByMeLabel: 'Người tạo',
	activeCreatedByMeValue: 'Chỉ của tôi',
	activeEnabledLabel: 'Đang bật',
	resultCountLabel: (count: number) => `${count} kết quả`,
	applyFilterLabel: 'Áp dụng bộ lọc',
	levelLabel: 'Cấp độ JLPT',
	statusLabel: 'Trạng thái',
	strokeCountLabel: 'Số nét',
	strokeCountMinPlaceholder: 'Tối thiểu',
	strokeCountMaxPlaceholder: 'Tối đa',
	radicalFilterLabel: 'Bộ thủ',
	radicalFilterPlaceholder: 'Ví dụ: 日, 口, 氵',
	createdByMeLabel: 'Chỉ của tôi',
	clearFilterLabel: 'Xóa lọc',
	searchLabel: 'Tìm kiếm',
	createLabel: 'Tạo Hán tự mới',
	backToListLabel: 'Quay lại quản lý Hán tự',
	tableTitle: 'Danh sách thẻ Hán tự',
	emptyTitle: 'Không có thẻ Hán tự phù hợp',
	emptyDescription: 'Thử đổi từ khóa hoặc điều chỉnh bộ lọc trạng thái.',
	emptyActionLabel: 'Tạo Hán tự mới',
	summaryFallbackLabel: 'Chưa có tóm tắt',
	tagsCountLabel: (count: number) => `${count} tag`,
	radicalCountLabel: (count: number) => `${count} bộ thủ`,
	columns: {
		kanji: 'Hán tự',
		strokeCount: 'Số nét',
		hanViet: 'Hán Việt',
		meaningVi: 'Nghĩa',
		level: 'Cấp độ',
		radicals: 'Bộ thủ',
		status: 'Trạng thái',
		createdAt: 'Tạo lúc',
		updatedAt: 'Cập nhật',
		actions: 'Thao tác',
	},
	actions: {
		edit: 'Sửa',
		delete: 'Xóa',
		confirmDelete: 'Bạn có chắc chắn muốn xóa Hán tự này?',
		saveDraft: 'Lưu bản nháp',
		downloadTemplate: 'Tải mẫu JSON',
		exportJson: 'Xuất JSON',
		importJson: 'Import JSON',
	},
	editor: {
		createPageTitle: 'Tạo Hán tự mới',
		editPageTitle: 'Chỉnh sửa Hán tự',
		createDescription: 'Nhập đầy đủ thông tin để tạo một thẻ Hán tự mới.',
		editDescription: 'Cập nhật nội dung Hán tự và lưu thay đổi.',
		notFoundLabel: 'Không tìm thấy dữ liệu Hán tự.',
		confirmLeaveTitle: 'Bạn chưa lưu thay đổi',
		confirmLeaveDescription: 'Bạn muốn hủy form này và rời trang, hay ở lại để tiếp tục chỉnh sửa?',
		confirmLeaveDiscardLabel: 'Hủy form và rời trang',
		confirmLeaveStayLabel: 'Ở lại chỉnh sửa',
	},
	toast: {
		createSuccess: 'Đã tạo Hán tự thành công.',
		updateSuccess: 'Đã cập nhật Hán tự thành công.',
		deleteSuccess: 'Đã xóa Hán tự thành công.',
		crudErrorFallback: 'Thao tác thất bại. Vui lòng thử lại.',
		downloadTemplateSuccess: 'Đã tải mẫu import kanji.',
		exportSuccess: 'Đã tải file export kanji.',
		importCommitSuccess: 'Đã commit import kanji thành công.',
		importInvalidJson: 'Tệp JSON không đúng định dạng import kanji.',
		importReadFailed: 'Không đọc được tệp JSON. Vui lòng kiểm tra lại.',
		importPreviewError: 'Không thể preview import kanji.',
		importCommitError: 'Không thể commit import kanji.',
	},
	form: {
		dialogTitleCreate: 'Tạo Hán tự mới',
		dialogTitleEdit: 'Chỉnh sửa Hán tự',
		dialogDescription: 'Biểu mẫu thao tác Hán tự trong quản trị nội dung.',
		loadingDetailLabel: 'Đang tải chi tiết Hán tự...',
		createActionLabel: 'Lưu mới',
		updateActionLabel: 'Lưu cập nhật',
		cancelActionLabel: 'Hủy',
		addItemLabel: 'Thêm',
		removeItemLabel: 'Xóa',
		sections: {
			basicTitle: 'Thông tin cơ bản',
			radicalsTitle: 'Bộ thủ (Radicals)',
			strokeOrderTitle: 'Thứ tự nét',
			radicalItemLabel: (index: number) => `Bộ thủ #${index}`,
		},
		fields: {
			titleLabel: 'Tiêu đề',
			titlePlaceholder: 'Ví dụ: 明',
			summaryLabel: 'Tóm tắt',
			summaryPlaceholder: 'Mô tả ngắn về Hán tự',
			kanjiLabel: 'Chữ Hán tự',
			kanjiPlaceholder: 'Ví dụ: 明',
			strokeCountLabel: 'Số nét',
			strokeCountPlaceholder: 'Ví dụ: 8',
			strokeOrderUrlLabel: 'Ảnh thứ tự nét',
			strokeOrderUrlHint: 'Upload ảnh hoặc GIF minh họa thứ tự viết nét.',
			onyomiLabel: 'Âm On (音読み)',
			onyomiPlaceholder: 'Nhập âm On rồi nhấn Enter',
			kunyomiLabel: 'Âm Kun (訓読み)',
			kunyomiPlaceholder: 'Nhập âm Kun rồi nhấn Enter',
			hanVietLabel: 'Âm Hán Việt',
			hanVietPlaceholder: 'Ví dụ: minh',
			meaningViLabel: 'Nghĩa tiếng Việt',
			meaningViPlaceholder: 'Ví dụ: sáng, rõ ràng',
			levelLabel: 'Cấp độ JLPT',
			statusLabel: 'Trạng thái',
			tagsLabel: 'Tags',
			tagsPlaceholder: 'Nhập tag rồi nhấn Enter',
			radicalCharacterLabel: 'Ký tự',
			radicalCharacterPlaceholder: 'VD: 日',
			radicalMeaningViLabel: 'Nghĩa',
			radicalMeaningViPlaceholder: 'VD: mặt trời',
		},
		addRadicalLabel: 'Thêm bộ thủ',
		removeRadicalLabel: 'Xóa bộ thủ',
		noRadicalsLabel: 'Chưa có bộ thủ nào.',
	},
	importDialog: {
		title: 'Import Hán tự từ JSON',
		description: 'Chọn tệp JSON, preview dữ liệu và commit batch import kanji.',
		fileLabel: 'Tệp JSON import',
		fileHint: 'Chỉ hỗ trợ tệp .json theo mẫu import kanji.',
		previewButtonLabel: 'Preview import',
		commitButtonLabel: 'Commit import',
		closeButtonLabel: 'Đóng',
		selectedFileLabel: 'Tệp đã chọn',
		summaryTitle: 'Tổng quan preview',
		totalItemsLabel: 'Tổng item',
		validItemsLabel: 'Hợp lệ',
		invalidItemsLabel: 'Không hợp lệ',
		emptyPreviewLabel: 'Chưa có dữ liệu preview. Hãy chọn file và bấm Preview import.',
		hasInvalidBlockLabel: 'Có item không hợp lệ, vui lòng chỉnh file rồi preview lại trước khi commit.',
		resultTitle: 'Kết quả preview theo từng dòng',
		columns: {
			rowNumber: 'Dòng',
			title: 'Tiêu đề',
			kanji: 'Hán tự',
			status: 'Trạng thái',
			errors: 'Lỗi',
		},
		statusValidLabel: 'Hợp lệ',
		statusInvalidLabel: 'Không hợp lệ',
	},
	previousPageLabel: 'Trang trước',
	nextPageLabel: 'Trang sau',
} as const

export const ADMIN_COMMON_CONTENT = {
	loadingLabel: 'Đang tải dữ liệu...',
	apiErrorFallback: 'Không tải được dữ liệu. Vui lòng thử lại.',
	pageInfoLabel: (page: number, total: number) => `Trang ${page} / ${total}`,
	notUpdatedLabel: 'Chưa cập nhật',
	emptyValueLabel: 'Chưa có',
	createActionLabel: 'Tạo mới',
	importErrorFallbackLabel: 'Có lỗi dữ liệu trong file import.',
	importWarningFallbackLabel: 'Có cảnh báo dữ liệu trong file import.',
	importErrorUnknownFieldLabel: (fieldPath: string) => `Dữ liệu không hợp lệ tại trường ${fieldPath}.`,
	importErrorByCode: {
		Sentence_ImportFieldRequired_400: 'Thiếu trường bắt buộc.',
		Sentence_ImportFieldTooLong_400: 'Giá trị vượt quá độ dài cho phép.',
		Sentence_ImportFieldInvalid_400: 'Giá trị không hợp lệ.',
		Sentence_ImportSpeakerIdNotSupported_400: 'Speaker không được hỗ trợ.',
		Vocabulary_ImportFieldRequired_400: 'Thiếu trường bắt buộc.',
		Vocabulary_ImportFieldTooLong_400: 'Giá trị vượt quá độ dài cho phép.',
		Vocabulary_ImportFieldInvalid_400: 'Giá trị không hợp lệ.',
		Vocabulary_ImportSentenceIdNotAllowed_400: 'Không được gửi sentence id trong import create-only.',
		Vocabulary_ImportDuplicateWritingInBatch_400: 'Trùng writing trong cùng batch import.',
		Vocabulary_ImportWritingAlreadyExists_400: 'Writing đã tồn tại trong hệ thống.',
		Grammar_ImportFieldRequired_400: 'Thiếu trường bắt buộc.',
		Grammar_ImportFieldTooLong_400: 'Giá trị vượt quá độ dài cho phép.',
		Grammar_ImportFieldInvalid_400: 'Giá trị không hợp lệ.',
		Grammar_ImportRelatedGrammarNotFound_404: 'Ngữ pháp liên quan không tìm thấy.',
		Grammar_ImportDuplicateRelation_400: 'Quan hệ ngữ pháp bị trùng lặp.',
		Grammar_ImportSentenceIdNotAllowed_400: 'Không được gửi sentence id trong import create-only.',
		Grammar_ImportSpeakerIdNotSupported_400: 'Speaker không được hỗ trợ.',
		Kanji_ImportFieldRequired_400: 'Thiếu trường bắt buộc.',
		Kanji_ImportFieldTooLong_400: 'Giá trị vượt quá độ dài cho phép.',
		Kanji_ImportFieldInvalid_400: 'Giá trị không hợp lệ.',
		Kanji_ImportDuplicateKanjiInBatch_400: 'Trùng Hán tự trong cùng batch import.',
		Kanji_ImportKanjiAlreadyExists_400: 'Hán tự đã tồn tại trong hệ thống.',
		Kanji_ImportRadicalsRequired_400: 'Thiếu danh sách bộ thủ.',
		Kanji_ImportDuplicateRadicalInItem_400: 'Bộ thủ trùng lặp trong cùng item.',
	},
} as const
