export const AUTH_LOGIN_COPY = {
  heading: 'Tacho Admin',
  subheading: 'Đăng nhập để quản lý nội dung và hệ thống.',
  badge: 'Studio Scholar',
  emailLabel: 'Email',
  emailPlaceholder: 'admin@tacho.app',
  passwordLabel: 'Mật khẩu',
  passwordPlaceholder: '••••••••',
  submitButton: 'Đăng nhập',
  loadingButton: 'Đang xác thực...',
  registerPrompt: '',
  registerLink: '',
  forgotPassword: 'Quên mật khẩu?',
  roleNote: 'Chỉ tài khoản Editor hoặc Admin mới có thể đăng nhập.',
  errorInvalidRole: 'Tài khoản này không có quyền truy cập trang quản trị.',
} as const

export const AUTH_REGISTER_COPY = {
  heading: 'Tạo tài khoản',
  subheading: 'Bắt đầu hành trình học tiếng Nhật của bạn.',
  displayNameLabel: 'Tên hiển thị',
  displayNamePlaceholder: 'Nguyễn Văn A',
  emailLabel: 'Email',
  emailPlaceholder: 'you@example.com',
  passwordLabel: 'Mật khẩu',
  passwordPlaceholder: '••••••••',
  submitButton: 'Đăng ký',
  loadingButton: 'Đang tạo tài khoản...',
  loginPrompt: 'Đã có tài khoản?',
  loginLink: 'Đăng nhập',
} as const
