import type {
  AiQuestionStatus,
  ChoukaiMondaiType,
  JlptLevel,
  OptionLabel,
  OptionType,
  PublishStatus,
  SectionType,
} from '@/types/jlptAdmin'

// ── Error Messages ───────────────────────────────────────────────────────────

export const JLPT_ADMIN_ERROR_MESSAGES: Record<string, string> = {
  Exam_NotFound_404: 'Không tìm thấy đề thi.',
  Exam_AlreadyPublished_400: 'Đề thi đã được phát hành trước đó.',
  Exam_NoSections_400: 'Đề thi chưa có section nào.',
  Exam_NoQuestions_400: 'Có section chưa có câu hỏi.',
  Exam_CannotDeletePublished_400: 'Không thể xóa đề thi đã phát hành.',
  Exam_CannotModifyPublished_400: 'Không thể sửa đề thi đã phát hành.',
  Exam_GroupNotFound_404: 'Không tìm thấy nhóm câu hỏi.',
  AiQuestion_NotFound_404: 'Không tìm thấy câu hỏi AI.',
  AiQuestion_AlreadyReviewed_400: 'Câu hỏi AI đã được duyệt hoặc từ chối trước đó.',
  AiQuestion_NoAudioScript_400: 'Nhóm câu hỏi chưa có script âm thanh.',
  Question_NotFound_404: 'Không tìm thấy câu hỏi.',
  Validation_400: 'Dữ liệu không hợp lệ. Vui lòng kiểm tra lại.',
  default: 'Không thể xử lý thao tác. Vui lòng thử lại.',
}

// ── Enum Labels ──────────────────────────────────────────────────────────────

export const JLPT_LEVEL_LABELS: Record<JlptLevel, string> = {
  N5: 'N5',
  N4: 'N4',
  N3: 'N3',
  N2: 'N2',
  N1: 'N1',
}

export const PUBLISH_STATUS_LABELS: Record<PublishStatus, string> = {
  Draft: 'Nháp',
  Published: 'Đã phát hành',
  Archived: 'Đã lưu trữ',
}

export const SECTION_TYPE_LABELS: Record<SectionType, string> = {
  Moji: 'Chữ / Từ vựng',
  Bunpou: 'Ngữ pháp',
  Dokkai: 'Đọc hiểu',
  Choukai: 'Nghe hiểu',
}

export const OPTION_LABEL_LABELS: Record<OptionLabel, string> = {
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
}

export const OPTION_TYPE_LABELS: Record<OptionType, string> = {
  Text: 'Chỉ văn bản',
  Image: 'Chỉ hình ảnh',
  TextAndImage: 'Văn bản và hình ảnh',
}

export const AI_QUESTION_STATUS_LABELS: Record<AiQuestionStatus, string> = {
  Pending: 'Chờ duyệt',
  Edited: 'Đã chỉnh sửa',
  Approved: 'Đã duyệt',
  Rejected: 'Đã từ chối',
}

export const CHOUKAI_MONDAI_TYPE_LABELS: Record<ChoukaiMondaiType, string> = {
  Mondai1: 'Dạng 1',
  Mondai2: 'Dạng 2',
  Mondai3: 'Dạng 3',
  Mondai4: 'Dạng 4',
  Mondai5: 'Dạng 5',
}

// ── Exam Page Content ────────────────────────────────────────────────────────

export const JLPT_EXAM_CONTENT = {
  pageTitle: 'Quản lý đề thi JLPT',
  heading: 'Quản lý đề thi JLPT',
  description: 'Tạo, quản lý đề thi, section, nhóm câu hỏi và câu hỏi cho kỳ thi JLPT.',
  searchPlaceholder: 'Tìm theo tiêu đề đề thi...',
  createLabel: 'Tạo đề thi',
  tableTitle: 'Danh sách đề thi',
  emptyTitle: 'Chưa có đề thi nào',
  emptyDescription: 'Hãy tạo đề thi JLPT đầu tiên hoặc thay đổi bộ lọc.',
  emptyActionLabel: 'Tạo đề thi',
  resultCountLabel: (count: number) => `${count} đề thi`,
  filterTitle: 'Bộ lọc đề thi',
  filterButtonLabel: 'Bộ lọc',
  filterDescription: 'Lọc theo cấp độ và trạng thái đề thi.',
  activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
  levelFilterPlaceholder: 'Chọn cấp độ',
  statusFilterPlaceholder: 'Chọn trạng thái',
  resetFiltersLabel: 'Xóa lọc',
  searchLabel: 'Tìm kiếm',
  allOptionLabel: 'Tất cả',
  previousPageLabel: 'Trang trước',
  nextPageLabel: 'Trang sau',
  paginationLabel: (currentPage: number, totalPage: number) => `Trang ${currentPage} / ${totalPage}`,
  noneSymbol: '—',
  columns: {
    title: 'Tiêu đề',
    level: 'Cấp độ',
    duration: 'Thời gian (phút)',
    status: 'Trạng thái',
    sections: 'Số section',
    creator: 'Người tạo',
    updatedAt: 'Cập nhật',
    actions: 'Thao tác',
  },
  actions: {
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    publish: 'Phát hành',
    openDetail: 'Quản lý chi tiết',
  },

  // ── Exam Form Dialog ───────────────────────────────────────────────────────
  createExamTitle: 'Tạo đề thi mới',
  createExamDescription: 'Nhập thông tin cơ bản cho đề thi JLPT mới.',
  editExamTitle: 'Chỉnh sửa đề thi',
  editExamDescription: 'Cập nhật thông tin đề thi JLPT.',
  titleFieldLabel: 'Tiêu đề',
  titleFieldPlaceholder: 'VD: JLPT N5 Mock Test 01',
  levelFieldLabel: 'Cấp độ JLPT',
  durationFieldLabel: 'Thời gian (phút)',
  durationFieldPlaceholder: 'VD: 120',
  cancelLabel: 'Hủy',
  createConfirmLabel: 'Tạo đề thi',
  saveLabel: 'Lưu thay đổi',
  examCreatedSuccess: 'Đã tạo đề thi thành công.',
  examUpdatedSuccess: 'Đã cập nhật đề thi thành công.',
  examDeletedSuccess: 'Đã xóa đề thi thành công.',
  examPublishedSuccess: 'Đã phát hành đề thi thành công.',
  createExamFailedFallback: 'Không thể tạo đề thi. Vui lòng thử lại.',
  updateExamFailedFallback: 'Không thể cập nhật đề thi. Vui lòng thử lại.',
  deleteExamFailedFallback: 'Không thể xóa đề thi. Vui lòng thử lại.',
  publishExamFailedFallback: 'Không thể phát hành đề thi. Vui lòng thử lại.',
  deleteExamConfirmTitle: 'Xác nhận xóa đề thi',
  deleteExamConfirmMessage: 'Bạn có chắc chắn muốn xóa đề thi này? Hành động này không thể hoàn tác.',
  confirmDeleteLabel: 'Xóa',
  confirmCancelLabel: 'Hủy',

  // ── Exam Detail Page ───────────────────────────────────────────────────────
  detailPageTitle: 'Chi tiết đề thi',
  backToList: 'Quay lại danh sách',
  examInfo: 'Thông tin đề thi',
  sectionsHeading: 'Danh sách Section',
  addSectionLabel: 'Thêm section',
  noSections: 'Chưa có section nào. Hãy thêm section đầu tiên.',

  // ── Section Form Dialog ────────────────────────────────────────────────────
  createSectionTitle: 'Thêm section mới',
  createSectionDescription: 'Tạo section cho đề thi.',
  editSectionTitle: 'Chỉnh sửa section',
  editSectionDescription: 'Cập nhật thông tin section.',
  sectionTypeFieldLabel: 'Loại section',
  sectionTypeFieldPlaceholder: 'Chọn loại section',
  orderIndexFieldLabel: 'Thứ tự',
  orderIndexFieldPlaceholder: 'VD: 0',
  durationMinutesFieldLabel: 'Thời gian (phút)',
  durationMinutesFieldPlaceholder: 'VD: 25',
  maxScoreFieldLabel: 'Điểm tối đa',
  maxScoreFieldPlaceholder: 'VD: 60',
  passScoreFieldLabel: 'Điểm qua',
  passScoreFieldPlaceholder: 'VD: 19',
  createSectionConfirmLabel: 'Thêm section',
  sectionCreatedSuccess: 'Đã thêm section thành công.',
  sectionUpdatedSuccess: 'Đã cập nhật section thành công.',
  sectionDeletedSuccess: 'Đã xóa section thành công.',
  createSectionFailedFallback: 'Không thể thêm section. Vui lòng thử lại.',
  updateSectionFailedFallback: 'Không thể cập nhật section. Vui lòng thử lại.',
  deleteSectionFailedFallback: 'Không thể xóa section. Vui lòng thử lại.',
  deleteSectionConfirmTitle: 'Xác nhận xóa section',
  deleteSectionConfirmMessage: 'Bạn có chắc chắn muốn xóa section này và tất cả nhóm câu hỏi bên trong?',

  // ── Question Group ─────────────────────────────────────────────────────────
  groupsHeading: 'Nhóm câu hỏi',
  addGroupLabel: 'Thêm nhóm',
  noGroups: 'Chưa có nhóm câu hỏi nào.',
  createGroupTitle: 'Thêm nhóm câu hỏi',
  createGroupDescription: 'Tạo nhóm câu hỏi mới cho section này.',
  editGroupTitle: 'Chỉnh sửa nhóm câu hỏi',
  editGroupDescription: 'Cập nhật thông tin nhóm câu hỏi.',
  instructionFieldLabel: 'Hướng dẫn',
  instructionFieldPlaceholder: 'VD: Chọn đáp án đúng nhất.',
  passageTextFieldLabel: 'Đoạn văn (Dokkai)',
  passageTextFieldPlaceholder: 'Đoạn văn đọc hiểu...',
  audioScriptFieldLabel: 'Script âm thanh (Choukai)',
  audioScriptFieldPlaceholder: 'Nhập script để sinh audio TTS...',
  mondaiTypeFieldLabel: 'Dạng bài nghe',
  mondaiTypeFieldPlaceholder: 'Chọn dạng bài',
  mondaiTypeNoneLabel: 'Không áp dụng',
  createGroupConfirmLabel: 'Thêm nhóm',
  groupCreatedSuccess: 'Đã thêm nhóm câu hỏi thành công.',
  groupUpdatedSuccess: 'Đã cập nhật nhóm câu hỏi thành công.',
  groupDeletedSuccess: 'Đã xóa nhóm câu hỏi thành công.',
  createGroupFailedFallback: 'Không thể thêm nhóm câu hỏi. Vui lòng thử lại.',
  updateGroupFailedFallback: 'Không thể cập nhật nhóm câu hỏi. Vui lòng thử lại.',
  deleteGroupFailedFallback: 'Không thể xóa nhóm câu hỏi. Vui lòng thử lại.',
  deleteGroupConfirmTitle: 'Xác nhận xóa nhóm câu hỏi',
  deleteGroupConfirmMessage: 'Bạn có chắc chắn muốn xóa nhóm câu hỏi này và tất cả câu hỏi bên trong?',
  generateAudioLabel: 'Sinh audio TTS',
  generateAudioSuccess: 'Đã sinh audio TTS thành công.',
  generateAudioFailedFallback: 'Không thể sinh audio. Vui lòng thử lại.',
  audioPlayerLabel: 'Nghe audio',

  // ── Question ───────────────────────────────────────────────────────────────
  questionsHeading: 'Câu hỏi',
  addQuestionLabel: 'Thêm câu hỏi',
  noQuestions: 'Chưa có câu hỏi nào trong nhóm này.',
  createQuestionTitle: 'Thêm câu hỏi',
  createQuestionDescription: 'Tạo câu hỏi mới cho nhóm này.',
  editQuestionTitle: 'Chỉnh sửa câu hỏi',
  editQuestionDescription: 'Cập nhật nội dung câu hỏi.',
  questionTextFieldLabel: 'Nội dung câu hỏi',
  questionTextFieldPlaceholder: 'Nhập nội dung câu hỏi...',
  explanationFieldLabel: 'Giải thích',
  explanationFieldPlaceholder: 'Nhập giải thích đáp án...',
  scoreFieldLabel: 'Điểm',
  scoreFieldPlaceholder: 'VD: 1',
  optionsHeading: 'Đáp án',
  optionTextFieldLabel: 'Nội dung đáp án',
  optionTextFieldPlaceholder: 'Nhập nội dung...',
  optionTypeFieldLabel: 'Loại đáp án',
  correctOptionLabel: 'Đáp án đúng',
  addOptionLabel: 'Thêm đáp án',
  removeOptionLabel: 'Xóa đáp án',
  createQuestionConfirmLabel: 'Thêm câu hỏi',
  questionCreatedSuccess: 'Đã thêm câu hỏi thành công.',
  questionUpdatedSuccess: 'Đã cập nhật câu hỏi thành công.',
  questionDeletedSuccess: 'Đã xóa câu hỏi thành công.',
  createQuestionFailedFallback: 'Không thể thêm câu hỏi. Vui lòng thử lại.',
  updateQuestionFailedFallback: 'Không thể cập nhật câu hỏi. Vui lòng thử lại.',
  deleteQuestionFailedFallback: 'Không thể xóa câu hỏi. Vui lòng thử lại.',
  deleteQuestionConfirmTitle: 'Xác nhận xóa câu hỏi',
  deleteQuestionConfirmMessage: 'Bạn có chắc chắn muốn xóa câu hỏi này?',
}

// ── AI Question Page Content ─────────────────────────────────────────────────

export const JLPT_AI_QUESTION_CONTENT = {
  pageTitle: 'Câu hỏi AI - JLPT',
  heading: 'Quản lý câu hỏi AI',
  description: 'Sinh câu hỏi bằng AI, biên tập, duyệt hoặc từ chối trước khi đưa vào ngân hàng câu hỏi.',
  generateLabel: 'Sinh câu hỏi AI',
  tableTitle: 'Danh sách câu hỏi AI',
  emptyTitle: 'Chưa có câu hỏi AI nào',
  emptyDescription: 'Hãy dùng tính năng sinh câu hỏi AI để bắt đầu.',
  emptyActionLabel: 'Sinh câu hỏi AI',
  resultCountLabel: (count: number) => `${count} câu hỏi`,
  searchPlaceholder: 'Tìm câu hỏi AI...',
  filterTitle: 'Bộ lọc câu hỏi AI',
  filterButtonLabel: 'Bộ lọc',
  filterDescription: 'Lọc theo cấp độ, loại section và trạng thái duyệt.',
  activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
  levelFilterPlaceholder: 'Chọn cấp độ',
  sectionTypeFilterPlaceholder: 'Chọn loại section',
  statusFilterPlaceholder: 'Chọn trạng thái',
  resetFiltersLabel: 'Xóa lọc',
  searchLabel: 'Tìm kiếm',
  allOptionLabel: 'Tất cả',
  previousPageLabel: 'Trang trước',
  nextPageLabel: 'Trang sau',
  noneSymbol: '—',
  columns: {
    topic: 'Chủ đề',
    level: 'Cấp độ',
    sectionType: 'Loại section',
    status: 'Trạng thái',
    creator: 'Người tạo',
    reviewer: 'Người duyệt',
    createdAt: 'Ngày tạo',
    actions: 'Thao tác',
  },
  actions: {
    viewDetail: 'Xem chi tiết',
    approve: 'Duyệt',
    reject: 'Từ chối',
    edit: 'Chỉnh sửa',
  },

  // ── Generate Dialog ────────────────────────────────────────────────────────
  generateTitle: 'Sinh câu hỏi bằng AI',
  generateDescription: 'AI sẽ sinh câu hỏi JLPT theo chủ đề và cấp độ bạn chọn.',
  topicFieldLabel: 'Chủ đề',
  topicFieldPlaceholder: 'VD: Từ vựng gia đình, Ngữ pháp て-form...',
  countFieldLabel: 'Số lượng câu hỏi',
  countFieldPlaceholder: 'VD: 5',
  levelFieldLabel: 'Cấp độ JLPT',
  sectionTypeFieldLabel: 'Loại section',
  cancelLabel: 'Hủy',
  generateConfirmLabel: 'Sinh câu hỏi',
  generateSuccess: 'Đã sinh câu hỏi AI thành công.',
  generateFailedFallback: 'Không thể sinh câu hỏi. Vui lòng thử lại.',

  // ── Detail Dialog ──────────────────────────────────────────────────────────
  detailTitle: 'Chi tiết câu hỏi AI',
  detailDescription: 'Xem, chỉnh sửa và duyệt nội dung câu hỏi AI đã sinh.',
  generatedDataLabel: 'Nội dung đã sinh',
  passageLabel: 'Đoạn văn',
  scriptLabel: 'Script',
  questionsLabel: 'Câu hỏi',
  editJsonLabel: 'Chỉnh sửa JSON',
  saveEditLabel: 'Lưu chỉnh sửa',
  approveLabel: 'Duyệt câu hỏi',
  rejectLabel: 'Từ chối',
  closeLabel: 'Đóng',
  approvedSuccess: 'Đã duyệt câu hỏi AI thành công.',
  rejectedSuccess: 'Đã từ chối câu hỏi AI.',
  editedSuccess: 'Đã lưu chỉnh sửa câu hỏi AI.',
  approveFailedFallback: 'Không thể duyệt câu hỏi. Vui lòng thử lại.',
  rejectFailedFallback: 'Không thể từ chối câu hỏi. Vui lòng thử lại.',
  editFailedFallback: 'Không thể lưu chỉnh sửa. Vui lòng thử lại.',
  approveConfirmTitle: 'Xác nhận duyệt câu hỏi',
  approveConfirmMessage: 'Câu hỏi AI sẽ được chuyển vào ngân hàng câu hỏi. Tiếp tục?',
  rejectConfirmTitle: 'Xác nhận từ chối câu hỏi',
  rejectConfirmMessage: 'Câu hỏi AI sẽ bị từ chối và không thể duyệt lại. Tiếp tục?',
  statusBadgeInfo: 'Trạng thái hiện tại',
  reviewerInfo: 'Người duyệt',
  reviewedAtInfo: 'Thời gian duyệt',
  invalidJsonError: 'Nội dung JSON không hợp lệ. Vui lòng kiểm tra lại.',
}
