import type {
  AiQuestionStatus,
  ChoukaiMondaiType,
  JlptLevel,
  OptionLabel,
  OptionType,
  PublishStatus,
  SectionType,
} from '@/types/jlptAdmin'

// ── Error Messages ───────────────────────────────────────────────────────────

export const JLPT_ADMIN_ERROR_MESSAGES: Record<string, string> = {
  Exam_NotFound_404: 'Không tìm thấy đề thi.',
  Exam_AlreadyPublished_400: 'Đề thi đã được phát hành trước đó.',
  Exam_NoSections_400: 'Đề thi chưa có section nào.',
  Exam_NoQuestions_400: 'Có section chưa có câu hỏi.',
  Exam_CannotDeletePublished_400: 'Không thể xóa đề thi đã phát hành.',
  Exam_CannotModifyPublished_400: 'Không thể sửa đề thi đã phát hành.',
  Exam_GroupNotFound_404: 'Không tìm thấy nhóm câu hỏi.',
  AiQuestion_NotFound_404: 'Không tìm thấy câu hỏi AI.',
  AiQuestion_AlreadyReviewed_400: 'Câu hỏi AI đã được duyệt hoặc từ chối trước đó.',
  AiQuestion_NoAudioScript_400: 'Nhóm câu hỏi chưa có script âm thanh.',
  Question_NotFound_404: 'Không tìm thấy câu hỏi.',
  Validation_400: 'Dữ liệu không hợp lệ. Vui lòng kiểm tra lại.',
  default: 'Không thể xử lý thao tác. Vui lòng thử lại.',
}

// ── Enum Labels ──────────────────────────────────────────────────────────────

export const JLPT_LEVEL_LABELS: Record<JlptLevel, string> = {
  N5: 'N5',
  N4: 'N4',
  N3: 'N3',
  N2: 'N2',
  N1: 'N1',
}

export const PUBLISH_STATUS_LABELS: Record<PublishStatus, string> = {
  Draft: 'Lưu nháp',
  Published: 'Xuất bản',
  Archived: 'Lưu trữ',
}

export const SECTION_TYPE_LABELS: Record<SectionType, string> = {
  Moji: 'Chữ / Từ vựng',
  Bunpou: 'Ngữ pháp',
  Dokkai: 'Đọc hiểu',
  Choukai: 'Nghe hiểu',
}

export const OPTION_LABEL_LABELS: Record<OptionLabel, string> = {
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
}

export const OPTION_TYPE_LABELS: Record<OptionType, string> = {
  Text: 'Chỉ văn bản',
  Image: 'Chỉ hình ảnh',
  TextAndImage: 'Văn bản và hình ảnh',
}

export const AI_QUESTION_STATUS_LABELS: Record<AiQuestionStatus, string> = {
  Pending: 'Chờ duyệt',
  Edited: 'Đã chỉnh sửa',
  Approved: 'Đã duyệt',
  Rejected: 'Đã từ chối',
}

export const CHOUKAI_MONDAI_TYPE_LABELS: Record<ChoukaiMondaiType, string> = {
  Mondai1: 'Mondai 1 — Hiểu vấn đề (課題理解)',
  Mondai2: 'Mondai 2 — Hiểu trọng điểm (ポイント理解)',
  Mondai3: 'Mondai 3 — Hiểu khái quát (概要理解)',
  Mondai4: 'Mondai 4 — Đáp ứng nhanh (即時応答)',
  Mondai5: 'Mondai 5 — Hiểu tổng hợp (統合理解)',
}

export const CHOUKAI_MONDAI_TYPE_DESCRIPTIONS: Record<ChoukaiMondaiType, string> = {
  Mondai1: 'Nghe hội thoại và chọn hành động/việc cần làm tiếp theo.',
  Mondai2: 'Nghe hội thoại và chọn lý do/trọng điểm chính.',
  Mondai3: 'Nghe đoạn nói và chọn ý chính/chủ đề tổng quát.',
  Mondai4: 'Nghe câu ngắn và chọn đáp án hồi đáp phù hợp.',
  Mondai5: 'Nghe đoạn dài, so sánh nhiều thông tin và chọn đáp án.',
}

// ── Exam Page Content ────────────────────────────────────────────────────────

export const JLPT_EXAM_CONTENT = {
  pageTitle: 'Quản lý đề thi JLPT',
  heading: 'Quản lý đề thi JLPT',
  description: 'Tạo, quản lý đề thi, section, nhóm câu hỏi và câu hỏi cho kỳ thi JLPT.',
  searchPlaceholder: 'Tìm theo tiêu đề đề thi...',
  createLabel: 'Tạo đề thi',
  tableTitle: 'Danh sách đề thi',
  emptyTitle: 'Chưa có đề thi nào',
  emptyDescription: 'Hãy tạo đề thi JLPT đầu tiên hoặc thay đổi bộ lọc.',
  emptyActionLabel: 'Tạo đề thi',
  resultCountLabel: (count: number) => `${count} đề thi`,
  filterTitle: 'Bộ lọc đề thi',
  filterButtonLabel: 'Bộ lọc',
  filterDescription: 'Lọc theo cấp độ và trạng thái đề thi.',
  activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
  levelFilterPlaceholder: 'Chọn cấp độ',
  statusFilterPlaceholder: 'Chọn trạng thái',
  resetFiltersLabel: 'Xóa lọc',
  searchLabel: 'Tìm kiếm',
  allOptionLabel: 'Tất cả',
  previousPageLabel: 'Trang trước',
  nextPageLabel: 'Trang sau',
  paginationLabel: (currentPage: number, totalPage: number) => `Trang ${currentPage} / ${totalPage}`,
  noneSymbol: '—',
  columns: {
    title: 'Tiêu đề',
    level: 'Cấp độ',
    duration: 'Thời gian (phút)',
    status: 'Trạng thái',
    sections: 'Số section',
    creator: 'Người tạo',
    updatedAt: 'Cập nhật',
    actions: 'Thao tác',
  },
  actions: {
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    publish: 'Phát hành',
    openDetail: 'Quản lý chi tiết',
    downloadTemplate: 'Tải template',
    importExam: 'Import đề thi',
    importGuide: 'Hướng dẫn import',
    exportJson: 'Xuất JSON',
  },

  // ── Exam Form Dialog ───────────────────────────────────────────────────────
  createExamTitle: 'Tạo đề thi mới',
  createExamDescription: 'Nhập thông tin cơ bản cho đề thi JLPT mới.',
  editExamTitle: 'Chỉnh sửa đề thi',
  editExamDescription: 'Cập nhật thông tin đề thi JLPT.',
  titleFieldLabel: 'Tiêu đề',
  titleFieldPlaceholder: 'VD: JLPT N5 Mock Test 01',
  levelFieldLabel: 'Cấp độ JLPT',
  durationFieldLabel: 'Thời gian (phút)',
  durationFieldPlaceholder: 'VD: 120',
  cancelLabel: 'Hủy',
  createConfirmLabel: 'Tạo đề thi',
  saveLabel: 'Lưu thay đổi',
  examCreatedSuccess: 'Đã tạo đề thi thành công.',
  examUpdatedSuccess: 'Đã cập nhật đề thi thành công.',
  examDeletedSuccess: 'Đã xóa đề thi thành công.',
  examPublishedSuccess: 'Đã phát hành đề thi thành công.',
  createExamFailedFallback: 'Không thể tạo đề thi. Vui lòng thử lại.',
  updateExamFailedFallback: 'Không thể cập nhật đề thi. Vui lòng thử lại.',
  deleteExamFailedFallback: 'Không thể xóa đề thi. Vui lòng thử lại.',
  publishExamFailedFallback: 'Không thể phát hành đề thi. Vui lòng thử lại.',
  deleteExamConfirmTitle: 'Xác nhận xóa đề thi',
  deleteExamConfirmMessage: 'Bạn có chắc chắn muốn xóa đề thi này? Hành động này không thể hoàn tác.',
  confirmDeleteLabel: 'Xóa',
  confirmCancelLabel: 'Hủy',

  // ── Exam Detail Page ───────────────────────────────────────────────────────
  detailPageTitle: 'Chi tiết đề thi',
  backToList: 'Quay lại danh sách',
  examInfo: 'Thông tin đề thi',
  sectionsHeading: 'Danh sách Section',
  addSectionLabel: 'Thêm section',
  noSections: 'Chưa có section nào. Hãy thêm section đầu tiên.',

  // ── Section Form Dialog ────────────────────────────────────────────────────
  createSectionTitle: 'Thêm section mới',
  createSectionDescription: 'Tạo section cho đề thi.',
  editSectionTitle: 'Chỉnh sửa section',
  editSectionDescription: 'Cập nhật thông tin section.',
  sectionTypeFieldLabel: 'Loại section',
  sectionTypeFieldPlaceholder: 'Chọn loại section',
  orderIndexFieldLabel: 'Thứ tự',
  orderIndexFieldPlaceholder: 'VD: 0',
  durationMinutesFieldLabel: 'Thời gian (phút)',
  durationMinutesFieldPlaceholder: 'VD: 25',
  maxScoreFieldLabel: 'Điểm tối đa',
  maxScoreFieldPlaceholder: 'VD: 60',
  passScoreFieldLabel: 'Điểm qua',
  passScoreFieldPlaceholder: 'VD: 19',
  createSectionConfirmLabel: 'Thêm section',
  sectionCreatedSuccess: 'Đã thêm section thành công.',
  sectionUpdatedSuccess: 'Đã cập nhật section thành công.',
  sectionDeletedSuccess: 'Đã xóa section thành công.',
  createSectionFailedFallback: 'Không thể thêm section. Vui lòng thử lại.',
  updateSectionFailedFallback: 'Không thể cập nhật section. Vui lòng thử lại.',
  deleteSectionFailedFallback: 'Không thể xóa section. Vui lòng thử lại.',
  deleteSectionConfirmTitle: 'Xác nhận xóa section',
  deleteSectionConfirmMessage: 'Bạn có chắc chắn muốn xóa section này và tất cả nhóm câu hỏi bên trong?',

  // ── Question Group ─────────────────────────────────────────────────────────
  groupsHeading: 'Nhóm câu hỏi',
  addGroupLabel: 'Thêm nhóm',
  noGroups: 'Chưa có nhóm câu hỏi nào.',
  createGroupTitle: 'Thêm nhóm câu hỏi',
  createGroupDescription: 'Tạo nhóm câu hỏi mới cho section này.',
  editGroupTitle: 'Chỉnh sửa nhóm câu hỏi',
  editGroupDescription: 'Cập nhật thông tin nhóm câu hỏi.',
  instructionFieldLabel: 'Hướng dẫn cho thí sinh',
  instructionFieldPlaceholder: 'VD: Chọn đáp án đúng nhất cho mỗi câu hỏi sau.',
  instructionFieldHint: 'Câu hướng dẫn hiển thị trên đầu nhóm câu hỏi (giống như đề bài Mondai trong đề thật).',
  passageTextFieldLabel: 'Đoạn văn đọc hiểu',
  passageTextFieldPlaceholder: 'Dán đoạn văn tiếng Nhật mà thí sinh phải đọc...',
  passageTextFieldHint: 'Chỉ điền cho section Đọc hiểu (Dokkai). Để trống nếu không phải bài đọc hiểu.',
  audioScriptFieldLabel: 'Kịch bản âm thanh (script)',
  audioScriptFieldPlaceholder: 'Dán nội dung tiếng Nhật mà thí sinh sẽ nghe (lời thoại / đoạn nói)...',
  audioScriptFieldHint: 'Chỉ điền cho section Nghe hiểu (Choukai). Sau khi lưu, có thể nhấn "Sinh audio TTS" để hệ thống tự tạo file nghe.',
  audioFileFieldLabel: 'Tải lên file âm thanh',
  audioFileFieldHint: 'Upload file âm thanh cho nhóm câu hỏi nghe hiểu (tùy chọn)',
  mondaiTypeFieldLabel: 'Dạng bài nghe (Mondai)',
  mondaiTypeFieldPlaceholder: 'Chọn dạng bài tương ứng với đề JLPT',
  mondaiTypeFieldHint: 'Chỉ áp dụng cho Choukai. Các dạng tương ứng với cấu trúc đề JLPT thật (Mondai 1–5).',
  mondaiTypeNoneLabel: 'Không áp dụng (chỉ Choukai)',
  orderIndexFieldHint: 'Số càng nhỏ thì nhóm xuất hiện càng sớm. Bắt đầu từ 0.',
  createGroupConfirmLabel: 'Thêm nhóm',
  groupCreatedSuccess: 'Đã thêm nhóm câu hỏi thành công.',
  groupUpdatedSuccess: 'Đã cập nhật nhóm câu hỏi thành công.',
  groupDeletedSuccess: 'Đã xóa nhóm câu hỏi thành công.',
  createGroupFailedFallback: 'Không thể thêm nhóm câu hỏi. Vui lòng thử lại.',
  updateGroupFailedFallback: 'Không thể cập nhật nhóm câu hỏi. Vui lòng thử lại.',
  deleteGroupFailedFallback: 'Không thể xóa nhóm câu hỏi. Vui lòng thử lại.',
  deleteGroupConfirmTitle: 'Xác nhận xóa nhóm câu hỏi',
  deleteGroupConfirmMessage: 'Bạn có chắc chắn muốn xóa nhóm câu hỏi này và tất cả câu hỏi bên trong?',
  generateAudioLabel: 'Sinh audio TTS',
  generateAudioSuccess: 'Đã sinh audio TTS thành công.',
  generateAudioFailedFallback: 'Không thể sinh audio. Vui lòng thử lại.',
  audioPlayerLabel: 'Nghe audio',

  // ── Question ───────────────────────────────────────────────────────────────
  questionsHeading: 'Câu hỏi',
  addQuestionLabel: 'Thêm câu hỏi',
  addQuestionFromAiLabel: 'Chọn từ câu hỏi AI',
  noQuestions: 'Chưa có câu hỏi nào trong nhóm này.',
  createQuestionTitle: 'Thêm câu hỏi',
  createQuestionDescription: 'Tạo câu hỏi mới cho nhóm này. Bạn có thể nhập tay hoặc nạp sẵn từ câu hỏi AI đã duyệt.',
  createQuestionFromAiHint: 'Mẹo: bạn có thể bấm "Chọn từ câu hỏi AI" để chèn dữ liệu sẵn, sau đó tinh chỉnh.',
  pickAiQuestionTitle: 'Chọn câu hỏi AI đã duyệt',
  pickAiQuestionDescription: 'Chọn một câu hỏi AI đã được duyệt để đưa vào nhóm. Nội dung sẽ được nạp sẵn vào form, bạn vẫn có thể chỉnh sửa trước khi lưu.',
  pickAiQuestionConfirmLabel: 'Dùng câu hỏi này',
  pickAiQuestionEmpty: 'Chưa có câu hỏi AI nào ở trạng thái Đã duyệt cho cấp độ / loại section này.',
  pickAiQuestionInvalidData: 'Câu hỏi AI không có dữ liệu hợp lệ.',
  editQuestionTitle: 'Chỉnh sửa câu hỏi',
  editQuestionDescription: 'Cập nhật nội dung câu hỏi.',
  questionTextFieldLabel: 'Nội dung câu hỏi',
  questionTextFieldPlaceholder: 'Nhập nội dung câu hỏi...',
  explanationFieldLabel: 'Giải thích',
  explanationFieldPlaceholder: 'Nhập giải thích đáp án...',
  imageFieldLabel: 'Hình ảnh câu hỏi',
  imageFieldHint: 'Tải lên hình ảnh minh họa cho câu hỏi (tùy chọn)',
  imageCaptionFieldLabel: 'Chú thích hình ảnh',
  imageCaptionFieldPlaceholder: 'Nhập chú thích cho hình ảnh...',
  scoreFieldLabel: 'Điểm',
  scoreFieldPlaceholder: 'VD: 1',
  optionsHeading: 'Đáp án',
  optionTextFieldLabel: 'Nội dung đáp án',
  optionTextFieldPlaceholder: 'Nhập nội dung...',
  optionTypeFieldLabel: 'Loại đáp án',
  optionImageLabel: 'Ảnh đáp án',
  optionTypeText: 'Văn bản',
  optionTypeImage: 'Hình ảnh',
  optionTypeTextAndImage: 'Văn bản + Hình ảnh',
  correctOptionLabel: 'Đáp án đúng',
  addOptionLabel: 'Thêm đáp án',
  removeOptionLabel: 'Xóa đáp án',
  createQuestionConfirmLabel: 'Thêm câu hỏi',
  questionCreatedSuccess: 'Đã thêm câu hỏi thành công.',
  questionUpdatedSuccess: 'Đã cập nhật câu hỏi thành công.',
  questionDeletedSuccess: 'Đã xóa câu hỏi thành công.',
  createQuestionFailedFallback: 'Không thể thêm câu hỏi. Vui lòng thử lại.',
  updateQuestionFailedFallback: 'Không thể cập nhật câu hỏi. Vui lòng thử lại.',
  deleteQuestionFailedFallback: 'Không thể xóa câu hỏi. Vui lòng thử lại.',
  deleteQuestionConfirmTitle: 'Xác nhận xóa câu hỏi',
  deleteQuestionConfirmMessage: 'Bạn có chắc chắn muốn xóa câu hỏi này?',

  // ── Import / Export ──────────────────────────────────────────────────────────
  importDialog: {
    title: 'Import đề thi từ JSON',
    description: 'Tải template, chọn file JSON và xem trước trước khi tạo đề thi.',
    downloadTemplateLabel: 'Tải template',
    importGuideLabel: 'Hướng dẫn import',
    fileLabel: 'Tệp JSON import',
    fileHint: 'Chỉ chấp nhận file .json. Tải template để biết định dạng đúng.',
    selectedFileLabel: 'File đã chọn',
    previewButtonLabel: 'Xem trước',
    commitButtonLabel: 'Tạo đề thi',
    closeButtonLabel: 'Đóng',
    hasInvalidBlockLabel: 'Dữ liệu có lỗi, không thể tạo đề thi.',
    emptyPreviewLabel: 'Chọn file JSON để xem trước.',
    summaryTitle: 'Kết quả kiểm tra',
    resultTitle: 'Chi tiết validation',
    statusValidLabel: 'Hợp lệ',
    statusInvalidLabel: 'Không hợp lệ',
    errorCountLabel: 'lỗi',
    warningCountLabel: 'cảnh báo',
    commitSuccess: 'Đã tạo đề thi thành công.',
    commitFailedFallback: 'Không thể tạo đề thi từ import. Vui lòng thử lại.',
    previewFailedFallback: 'Không thể kiểm tra file. Vui lòng thử lại.',
    importInvalidJson: 'File JSON không hợp lệ.',
    importReadFailed: 'Không thể đọc file.',
  },
  exportExam: {
    success: 'Đã tải file export thành công.',
    failedFallback: 'Không thể tải file export. Vui lòng thử lại.',
  },
}

// ── AI Question Page Content ─────────────────────────────────────────────────

export const JLPT_AI_QUESTION_CONTENT = {
  pageTitle: 'Câu hỏi AI - JLPT',
  heading: 'Quản lý câu hỏi AI',
  description: 'Sinh câu hỏi bằng AI, biên tập, duyệt hoặc từ chối trước khi đưa vào ngân hàng câu hỏi.',
  generateLabel: 'Sinh câu hỏi AI',
  tableTitle: 'Danh sách câu hỏi AI',
  emptyTitle: 'Chưa có câu hỏi AI nào',
  emptyDescription: 'Hãy dùng tính năng sinh câu hỏi AI để bắt đầu.',
  emptyActionLabel: 'Sinh câu hỏi AI',
  resultCountLabel: (count: number) => `${count} câu hỏi`,
  searchPlaceholder: 'Tìm câu hỏi AI...',
  filterTitle: 'Bộ lọc câu hỏi AI',
  filterButtonLabel: 'Bộ lọc',
  filterDescription: 'Lọc theo cấp độ, loại section và trạng thái duyệt.',
  activeFilterSummaryLabel: (count: number) => `${count} bộ lọc đang bật`,
  levelFilterPlaceholder: 'Chọn cấp độ',
  sectionTypeFilterPlaceholder: 'Chọn loại section',
  statusFilterPlaceholder: 'Chọn trạng thái',
  resetFiltersLabel: 'Xóa lọc',
  searchLabel: 'Tìm kiếm',
  allOptionLabel: 'Tất cả',
  previousPageLabel: 'Trang trước',
  nextPageLabel: 'Trang sau',
  noneSymbol: '—',
  columns: {
    topic: 'Chủ đề',
    level: 'Cấp độ',
    sectionType: 'Loại section',
    status: 'Trạng thái',
    questionGroupId: 'Đề thi đích',
    creator: 'Người tạo',
    reviewer: 'Người duyệt',
    createdAt: 'Ngày tạo',
    actions: 'Thao tác',
  },
  actions: {
    viewDetail: 'Xem chi tiết',
    approve: 'Duyệt',
    reject: 'Từ chối',
    edit: 'Chỉnh sửa',
  },

  // ── Generate Dialog ────────────────────────────────────────────────────────
  generateTitle: 'Sinh câu hỏi bằng AI',
  generateDescription: 'AI sẽ sinh câu hỏi JLPT theo chủ đề và cấp độ bạn chọn.',
  topicFieldLabel: 'Chủ đề',
  topicFieldPlaceholder: 'VD: Từ vựng gia đình, Ngữ pháp て-form...',
  countFieldLabel: 'Số lượng câu hỏi',
  countFieldPlaceholder: 'VD: 5',
  levelFieldLabel: 'Cấp độ JLPT',
  sectionTypeFieldLabel: 'Loại section',
  questionGroupIdFieldLabel: 'Nhóm câu hỏi đích',
  questionGroupIdFieldPlaceholder: 'ID nhóm câu hỏi (tùy chọn)',
  questionGroupIdFieldHint: 'Nếu chỉ định, câu hỏi khi duyệt sẽ tự động thêm vào nhóm này.',
  cancelLabel: 'Hủy',
  generateConfirmLabel: 'Sinh câu hỏi',
  generateSuccess: 'Đã sinh câu hỏi AI thành công.',
  generateFailedFallback: 'Không thể sinh câu hỏi. Vui lòng thử lại.',

  // ── Detail Dialog ──────────────────────────────────────────────────────────
  detailTitle: 'Chi tiết câu hỏi AI',
  detailDescription: 'Xem, chỉnh sửa và duyệt nội dung câu hỏi AI đã sinh.',
  generatedDataLabel: 'Nội dung đã sinh',
  passageLabel: 'Đoạn văn',
  scriptLabel: 'Script',
  questionsLabel: 'Câu hỏi',
  difficultyLabel: 'Độ khó',
  qualityScoreLabel: 'Điểm chất lượng',
  requiresReviewLabel: 'Cần review thủ công',
  duplicatesLabel: 'Câu hỏi tương tự',
  skillTagsLabel: 'Kỹ năng',
  questionGroupIdLabel: 'Đề thi đích',
  editJsonLabel: 'Chỉnh sửa JSON',
  saveEditLabel: 'Lưu chỉnh sửa',
  approveLabel: 'Duyệt câu hỏi',
  rejectLabel: 'Từ chối',
  closeLabel: 'Đóng',
  approvedSuccess: 'Đã duyệt câu hỏi AI thành công.',
  rejectedSuccess: 'Đã từ chối câu hỏi AI.',
  editedSuccess: 'Đã lưu chỉnh sửa câu hỏi AI.',
  approveFailedFallback: 'Không thể duyệt câu hỏi. Vui lòng thử lại.',
  rejectFailedFallback: 'Không thể từ chối câu hỏi. Vui lòng thử lại.',
  editFailedFallback: 'Không thể lưu chỉnh sửa. Vui lòng thử lại.',
  approveConfirmTitle: 'Xác nhận duyệt câu hỏi',
  approveConfirmMessage: 'Câu hỏi AI sẽ được chuyển vào ngân hàng câu hỏi. Tiếp tục?',
  approveConfirmMessageWithGroup: 'Câu hỏi AI sẽ được tạo thực tế vào nhóm câu hỏi đích. Tiếp tục?',
  rejectConfirmTitle: 'Xác nhận từ chối câu hỏi',
  rejectConfirmMessage: 'Câu hỏi AI sẽ bị từ chối và không thể duyệt lại. Tiếp tục?',
  statusBadgeInfo: 'Trạng thái hiện tại',
  reviewerInfo: 'Người duyệt',
  reviewedAtInfo: 'Thời gian duyệt',
  invalidJsonError: 'Nội dung JSON không hợp lệ. Vui lòng kiểm tra lại.',

  // ── AI Generate in Exam Detail ────────────────────────────────────────────
  generateAiForGroupLabel: 'Sinh câu hỏi AI',
  generateAiResultTitle: 'Kết quả sinh câu hỏi AI',
  generateAiResultDescription: 'Xem và duyệt câu hỏi AI vừa sinh cho nhóm này.',
  allProcessedLabel: 'Đã xử lý tất cả câu hỏi',
  pendingCountLabel: (count: number) => `${count} câu chờ duyệt`,
}
